### ISSUE TITLE
Should subprocess Work On Mono?

### ISSUE THREAD

**Issue by slide** [IronLanguages/ironpython2#126]
_From @ironpythonbot on December 9, 2014 18:12_

I've spent the last couple of days doing searches, digging through code,
looking at old forum posts, looking at online documentation, and checking the
mailing list. I'm still not sure so I'll throw it out there:  

Should I be able to import the subprocess module and use it on Mono (because I
don't seem to be able to)?  

If I should, any ideas on what I'm doing wrong? If I shouldn't, is there:  
1. Intent to have it work in the future? If so, is there an issue # or something I could be tracking against? 
2. Any documentation that makes this clear?  

I'm using the following versions/systems:  

IronPython v2.7.3  
Xubuntu 13.10 64-bit running Mono 2.10.8.1 (Debian 2.10.8.1-5ubuntu2)  
Windows 7 Enterprise 64-bit running .NET Framework 4.5.1 (and a few of the
older .NET versions as well)  
# Windows

```
...>"C:\Program Files (x86)\IronPython 2.7\ipy64.exe"
IronPython 2.7.3 (2.7.0.40) on .NET 4.0.30319.18408 (64-bit)
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> 
```

I can proceed and do things like _ subprocess.call('<some program>') _ just
fine.  
# Linux

```
...$ mono ../IronPython/ipy64.exe
IronPython 2.7.3 (2.7.0.40) on Mono 4.0.30319.1 (64-bit)
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "../IronPython/Lib/subprocess.py", line 430, in <module>
ImportError: No module named fcntl
>>>
```

Some things I looked at when trying to figure this out:  
- [ IronPython Work Item 15512 ](http://ironpython.codeplex.com/workitem/15512) : Seems to indicate subprocess was implemented and working as of 2.7B2 (other [ release notes ](https://ironpython.codeplex.com/releases/view/54498) and [ mailing list items ](http://lists.ironpython.com/htdig.cgi/users-ironpython.com/2011-February/014286.html) seem to back this up). Not explicit if it was tested/supposed to be working on Mono or not, but it seems that by default the assumption should be yes unless it explicitly says otherwise. 
- [ IronPython Work Item 23983 ](http://ironpython.codeplex.com/workitem/23983) : Similar to the other one. Also marked as closed out. 
- [ IronPython FAQ ](http://ironpython.codeplex.com/wikipage?title=FAQ) : I didn't see anything about it in the FAQ 
- [ IronPython Mailing List Archive ](http://lists.ironpython.com/pipermail/users-ironpython.com/) : Didn't appear to be anything recent (lots of stuff back from pre-2.7B2 and then with the fix in 2.7B2) 
- [ IronPython Cookbook: Launching Sub-Processes ](http://www.ironpython.info/index.php?title=Launching_Sub-Processes) : Provides a workaround using System.Diagnostic.Processes instead of subprocess that still works. Has some links to a partial subprocess module implementation in C# written by jdhardy back in 2008 (who I see is still heavily involved and a coordinator in this project). Not sure if that was ever completed or integrated into IronPython (I don't see it in the source code package from 2.7.3 though). Other link is dead. The cookbook page says _ Because the select module is not available, you can't use the subprocess module in IronPython _ . I'm guessing that is somewhat outdated, as the select module doesn't seem to have anything to do with the current issue (possibly back in 2007 when it was written) and there haven't been any significant updates to that page since it was first written.  

Looking at the source code for subprocess.py, what appears to keep the module
from being loaded (unknown if it would work even if you got it loading, but
hey...) is listed below. Note that these assume the POSIX codepath is the one
that should be taken (which is what currently is being taken; if ultimately
the Windows codepath is what we are going for, a different set of changes
would need to be made to subprocess.py).  
- Missing fcntl module. This is a [ Unix specific module ](http://docs.python.org/2/library/fcntl.html) that is a built-in module provided by the Python interpreter itself on Linux. The IronPython interpreter does not have fcntl as a built-in. The uses of fcntl by subprocess are all fairly contained around safely/properly handling duplicated stdio handles when child processes are spawned. The particular symbols missing are the fcntl function itself, FD_CLOEXEC, F_GETFD, and F_SETFD. 
- Missing certain members from the os module. In particular the WIFSIGNALED, WTERMSIG, WIFEXITED, WEXITSTATUS, and WNOHANG symbols. Even though they are from the os module, the os module actually gets them from the posix module on Linux. Now the posix module is present with IronPython but it doesn't have these symbols. All of the uses of these symbols in subprocess are fairly well contained as well and deal with properly waiting for and setting the return code for the exiting child process.  

Any thoughts?  
## Work Item Details

**Original CodePlex Issue:**    [Issue 34751](http://ironpython.codeplex.com/workitem/34751)
**Status:** Active
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Dec 18, 2013 at 10:17 PM
**Reported by:**    TeddyP
**Updated on:** Nov 7 at 2:42 PM
**Updated by:** tcalmant

_Copied from original issue: IronLanguages/main#1094_

**Comment by slide** [comment]
_From @ironpythonbot on December 9, 2014 18:12_

On _2013-12-20 14:55:35 UTC_, **jdhardy** commented:

First off, I appreciate your thoroughness. I'm not sure I've ever but this much detail into a bug report.

The short version is that no, it probably doesn't work, because I don't think it's ever been tested and then made to work. I would love for it to be supported on Mono, but I just don't have the time to do it right now myself. One area that may cause issues
 is the subprocess (and multiprocessing) might do things to the process state that Mono doesn't like (see

System.Unix.Native.Syscall.fork is commented out, for example). 

If you want to tackle it, 
Mono.Unix.Native is probably going to be your friend to fill in IronPython's posix support. (Interestingly, IP doesn't have a real posix module right now; the 'nt' module is re-named to 'posix' when running on Unix...)

One thing to keep in mind is that the same DLLs have to work on both; happily, DLL imports are not resolved unless used, and I'm OK with it failing if someone tries to call a posix method on Windows (this is how the msvcrt module fails on non-Windows machines,
 for example). signal.cs is another example of how it can be handled, where the module needs to be implemented on both platforms. Finally, it's OK to use reflection to look for Mono.Posix.dll and pull the values at runtime, and just ignore them at compile time.

There doesn't seem to be issues open for fcntl or a real posix module, so feel free to open them if needed.

**Comment by slide** [comment]
_From @ironpythonbot on December 9, 2014 18:12_

On _2013-12-21 00:21:33 UTC_, **TeddyP** commented:

Thanks for the response. I probably won't be able to tackle it myself now either. This was a rabbit hole I went down trying to work around a limitation of another tool that uses IronPython to provide extensibility. I was trying to use subprocess as a workaround
 for that tool's limitation (the System.Diagnostics.Process workaround manages to get me the functionality I need in this particular case, but it seems to lack the elegance of using subprocess so I went digging).

I'm glad to have the question answered at least. Hopefully folks with the same question will stumble across this post without having to do all the digging around I did. Perhaps it will be a good starting point for whoever eventually decides to tackle it as
 well. 

I wonder if it would be possible to have the subprocess module in IronPython throw an exception that clearly indicates it isn't currently supported on non-Windows platforms if it detects it isn't running on Windows? It looks like there is some customization
 of the subprocess module released with IronPython as compared to what comes with the corresponding version of Python (I diff'ed the 2.7.3 version of both and they were largely the same but did have a few differences), so this might be a quick, easy, and efficient
 way of conveying the information.

**Comment by slide** [comment]
Importing subprocess actually works now and much of the functionality is working.

**Comment by slide** [comment]
The subprocess module imports correctly now, though all functionality is not there.

**Comment by Hantse** [comment]
Hello,

Some solution about fcntl ?
