### ISSUE TITLE
Compiled .exe gives"URI formats are not supported"-error when importing pyVISA package

### ISSUE THREAD

**Issue by slide** [IronLanguages/ironpython2#136]
_From @ironpythonbot on December 9, 2014 17:51_

For an application I need te pyVISA Python package. I can run the application
fine via cmd "ipy.exe Program.py", but when running the compiled exe (with
pyc.py) I get following error and the app terminates:  

```
Unhandled Exception: System.ArgumentException: URI formats are not supported.  
at Microsoft.Scripting.Actions.Calls.MethodCandidate.Caller.Call(Object[args, Boolean& shouldOptimize)  
at IronPython.Runtime.Types.BuiltinFunction.BuiltinFunctionCaller`6.Call5(CallSite site, CodeContext context, TFuncType func, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)  
at System.Dynamic.UpdateDelegates.UpdateAndExecute7[T0,T1,T2,T3,T4,T5,T6,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6)  
at IronPython.Runtime.Importer.Import(CodeContext context, String fullName, PythonTuple from, Int32 level)  
at IronPython.Runtime.Operations.PythonOps.InitializeModule(Assembly precompiled, String main, String[ references)  
at PythonMain.Main()  
```

The Program.py looks like this:  

``` python
import sys  
sys.path.append(r'C:\Program Files\IronPython 2.6 for .NET 4.0\Lib')  
sys.path.append(r'C:\Program Files\IronPython 2.6 for .NET 4.0\Lib\site-packages')  
print sys.path  

import visa  

print ""  
print "Hello, World!"  
```

I've tested it on both IP 2.7 and 2.6  
## Work Item Details

**Original CodePlex Issue:**    [Issue 29967](http://ironpython.codeplex.com/workitem/29967)
**Status:** Active
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Jan 13, 2011 at 4:27 PM
**Reported by:**    debbes
**Updated on:** May 30, 2013 at 5:54 PM
**Updated by:** awaiK

_Copied from original issue: IronLanguages/main#913_

**Comment by slide** [comment]
_From @ironpythonbot on December 9, 2014 17:51_

On _2011-02-14 22:10:40 UTC_, **geniedelsh** commented:

I get the same error when importing VISA via ironpython. What I get translates to the following in Pythons ConfigParser.py:

fp = open("file:///C:/Users/eugene/Project/Win32/Debug/IronPython.DLL/share/pyvisa/.pyvisarc")

If I remove the 'file:///' (i.e. URI) everything is fine. 

Now what in IronPython is passing filesystem paths out like that? And how do I fix this without patching my Python installation?

**Comment by slide** [comment]
_From @ironpythonbot on December 9, 2014 17:51_

On _2011-07-28 16:17:27 UTC_, **debbes** commented:

Yes, indeed. That did the trick for me to. Although it wasn't that obvious, I patched the ConfigParser.py file in my "C:\Program Files\IronPython 2.6 for .NET 4.0\Lib" folder like this:

Search for the only instance: 

fp = open(filename) 

and replace it with: 

fp = open(str(filename).strip(r"file:///")) 

Maybe it has to do with calling a file like that inside a .dll file, that's causing the problem?

**Comment by slozier** [comment]
I haven't been able to reproduce this failure. How is the failing program produced?

**Comment by spidermonkey1187** [comment]
The following shows where this is happening:

1.  // Adding source
2.  ScriptSource Source = engine.CreateScriptSourceFromFile ( @"fully qualified path to module, tested and works" );
3.  // Assigning execution of source to an object, I’ve assigned two sources to this scope. Wrong thing to do?
4.  object mObject = Source.Execute ( ipyScope );
5.  // Declaring a class object in scope, or something like that
6.  dynamic Var = ipyScope.GetVariable ( "myModule" );  // <---- This produces the issue, will do try catch after lunch

I truly appreciate you guys helping me with this.  Will get back to you after memorial day stuff is over with daughter.

**Comment by slide** [comment]
You are seeing this specifically with pyVISA?

**Comment by spidermonkey1187** [comment]
No I am able to use pyVisa instruments without difficulty.

**Comment by spidermonkey1187** [comment]
My apologies I responded to the wrong thread.  Yes this is happening when importing pyvisa via C# and IronPython.

**Comment by slide** [comment]
Can you provide a simple reproduction case? We used pyVISA at work with IronPython with no issues, so I'd like to see what you are trying to do?

**Comment by spidermonkey1187** [comment]
Slide,

In my reply above when performing a scope.GetVariable() the issue presented.  I merely verified that the ConfigParser.py was still an issue and that adding the .split to fopen is a work around.  Now I am not at all an expert on python so if there is something I'm leaving out please let me know and I can get more details.

**Comment by slide** [comment]
Can you provide the exact code so we aren't guessing as to what exactly you are doing?

**Comment by spidermonkey1187** [comment]
Slide,

Here is what is happening:
``

**Comment by slide** [comment]
I'm unable to reproduce this at all. I compiled the Program.py
