### ISSUE TITLE
reversed() implementation is different with cpython

### ISSUE THREAD

**Issue by slide** [IronLanguages/ironpython2#140]
_From @ironpythonbot on December 9, 2014 17:31_

```
E:\2.5test\ironpythonCompatableFor2.5\25\Lib>ipy  
IronPython console: 2.0  
Copyright (c) Microsoft Corporation. All rights reserved.  

>>> n = 10  
d = range(n)  
it = reversed(d)  
d[1:] = []  
len(it)  
10  
list(it)  
Traceback (most recent call last):  
File , line 0, in ##304  
File , line 0, in _stub_##255  
IndexError: index out of range: 9  
^Z  
```

```
E:\2.5test\ironpythonCompatableFor2.5\25\Lib>python  
Python 2.5 (r25:51908, Sep 19 2006, 09:52:17) [MSC v.1310 32 bit (Intel)] on
win  
32  
Type "help", "copyright", "credits" or "license" for more information.  
n = 10  
d = range(n)  
it = reversed(d)  
d[1:] =[]  
len(it)  
0  
list(it)  
[]  
```
## Work Item Details

**Original CodePlex Issue:**    [Issue 23915](http://ironpython.codeplex.com/workitem/23915)
**Status:** Active
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Jul 28, 2009 at 12:08 AM
**Reported by:**    dfugate
**Updated on:** Feb 22, 2013 at 2:12 AM
**Updated by:** jdhardy
**Custom value:**   Reported internally at Microsoft.
**Test:**   test_iterlen.py
**CreatedDate:**    1/9/2008
**NewInternalID:**  409735
**OldInternalID:**  365854
**AreaPath:**   IronPython\Python25
#### Plaintext Attachments

[CodePlex Issue #23915 Plain Text Attachments](https://gist.github.com/8779b7f0019c1099d094)

_Copied from original issue: IronLanguages/main#633_

**Comment by slide** [comment]
_From @ironpythonbot on December 9, 2014 17:31_

On _2011-01-29 06:35:03 UTC_, **rjnienaber** commented:

This behaviour has subsequently changed in CPython 2.6 and 2.7 to the following:
c:\Python27\python.exe testcase-23915.py
Traceback (most recent call last):
File "testcase-23915.py", line 5, in <module>

len(it)
TypeError: object of type 'listreverseiterator' has no len() 

Ironpython 2.6.2 and 2.7b1 behaviour is the following:
ipy27 testcase-23915.py
Traceback (most recent call last):
File "testcase-23915.py", line 5, in <module>
TypeError: len() of unsized object

The behaviour seems correct, it's just the error messages that need to be changed.

**Comment by slozier** [comment]
Closing this since https://github.com/IronLanguages/ironpython2/issues/387 has a better description of the remaining issue.
