### ISSUE TITLE
Clean-up migrated wiki pages

### ISSUE THREAD

**Issue by slozier** [IronLanguages/ironpython2#151]
Although the wiki is mostly out of date there are probably a few pages which are worth moving over.

What we probably want to exclude:
- IronRuby specific stuff
- Outdated technical stuff (e.g. Working With Mercurial)

**Comment by slide** [comment]
The wiki looks like it was migrated already, do we just need to clean stuff up?

**Comment by slozier** [comment]
Yes, I did migrate it and did a preliminary cleanup when I did, but there's a lot more cleanup that could be done.

**Comment by slide** [comment]
Wiki pages were moved into files in the Documentation area.
