### ISSUE TITLE
Disable large file tests in test_mmap

### ISSUE THREAD

**Issue by slozier** [IronLanguages/ironpython2#168]
The large file tests (test_large_filesize and test_large_offset) in test_mmap create very large files and can be somewhat slow. These were disabled (on purpose) in IronLanguages/main because the test was run via the regrtest launcher. It would be nice to be able to disable them using the new test running (without having to modify the source).

**Comment by slide** [comment]
This is fixed in #170

**Comment by slide** [comment]
Fixed!
