### ISSUE TITLE
clr Modules return False with inspect.ismodule

### ISSUE THREAD

**Issue by gtalarico** [IronLanguages/ironpython2#190]
`inspect.ismodule()` should return `True` when passed any module object correct?

Reproducible below:

```
>>> import os
>>> os
<module 'os' from 'C:\Program Files (x86)\IronPython-2.7.7\Lib\os.py'>
>>> inspect.ismodule(os)
True

>>> import clr
>>> clr.References[3]
<Assembly IronPython.Wpf, Version=2.7.7.0, Culture=neutral, PublicKeyToken=7f709c5b713576e1>
>>> a = clr.References[3]
>>> vars(a)
{'IronPython': <module 'IronPython' (CLS module from IronPython.Wpf, Version=2.7.7.0, Culture=neutral, PublicKeyToken=7f709c5b713576e1)>}
>>> m = vars(a)['IronPython']
>>> m
<module 'IronPython' (CLS module from IronPython.Wpf, Version=2.7.7.0, Culture=neutral, PublicKeyToken=7f709c5b713576e1)>
>>> inspect.ismodule(m)
False

>>> import IronPython
>>> inspect.ismodule(IronPython)
False
>>>
```

Same results below if checking `isinstance(m, types.ModuleType)`

```
>>> isinstance(m, inspect.types.ModuleType)
False
>>> isinstance(os, inspect.types.ModuleType)
True
```

**Comment by gtalarico** [comment]
Hi @slozier thanks for responding to my other issue :) 
Can you tell me if this one is by design or a bug?

**Comment by slozier** [comment]
I'm not sure if they were excluded by design or if it just happened that way. It's returning False because it looks like the CLR namespaces (e.g. IronPython, System) are of "namespace" type while the Python modules (e.g. sys, os) are of "module" type.

Would having the namespace types also be modules be something that would be useful for you or is it just a peculiarity you noticed?

**Comment by gtalarico** [comment]
I guess I am a little confused between modules vs namespaces types in Python since
namespace object's repr() says:  '<module ..', 

```
>>> os
<module 'os' from 'C:\Program Files (x86)\IronPython-2.7.7\Lib\os.py'>
>>> type(os)
<type 'module'>
>>>

>>> wpf_ref = clr.References[3]
>>> wpf_ref
<Assembly IronPython.Wpf, Version=2.7.7.0, Culture=neutral, PublicKeyToken=7f709c5b713576e1>
>>> vars(wpf_ref)
{'IronPython': <module 'IronPython' (CLS module from IronPython.Wpf, Version=2.7.7.0, Culture=neutral, PublicKeyToken=7f709c5b713576e1)>}
>>> wpf_module = vars(wpf_ref)['IronPython']
>>> wpf_module  # <<< Note how repr include <'module

# HERE
<module 'IronPython' (CLS module from IronPython.Wpf, Version=2.7.7.0, Culture=neutral, PublicKeyToken=7f709c5b713576e1)>

>>> type(wpf_module)
<type 'namespace#'>
```

To give you some background, I was working on a toll to batch generate python stub files for DLLs
so I can use Autocomplete in Atom Editor + Visual Studio Code and I needed to check if it's a object is not a module to decide if I should keep going recursively into it, but I might be going about it the wrong way:
https://github.com/gtalarico/ironpython-stubs/blob/master/make_stubs.py#L47
https://github.com/gtalarico/ironpython-stubs

**Comment by slozier** [comment]
I see, well if you're just going through .NET assemblies then they will all be namespaces. I would suggest doing something like (instead of the string check):
```Python
def is_namespace(obj):
    return isinstance(obj, type(System)):
```

**Comment by gtalarico** [comment]
That makes sense, thanks!
