### ISSUE TITLE
Using OrderedDict causes inspect.stack() to report wrong frames

### ISSUE THREAD

**Issue by gtalarico** [IronLanguages/ironpython2#192]
Importing OrderedDict causes inspect.stack() to report wrong frame:

![image](https://user-images.githubusercontent.com/9513968/27565101-19897c5c-5aaa-11e7-95d8-71608667306d.png)

Repro:
```
import inspect
from collections import OrderedDict

def test():
    x = True
    print(inspect.currentframe().f_locals)
    # {'x': True}
    d = dict()
    print(inspect.currentframe().f_locals)
    # {'x': True, 'd':{} }
    o = OrderedDict()
    print(inspect.currentframe().f_locals)
    # {'self': OrderedDict(), 'args': (), 'kwds': {}, 'root': [[...], [...], None]}
    # Should be: {'x': True, 'd':{}, o:OrderedDict() }

test()
```

Same happens using `stack()[0] `. 

I am not sure if this is cause by OrderedDict or inspect, but I have not seen it happen with any other types. For example, behaves as expected with namedtuples

![image](https://user-images.githubusercontent.com/9513968/27565216-f9011318-5aaa-11e7-8ba7-97d2a06af0b0.png)

**Comment by slozier** [comment]
Thanks for the report. Looks like IronLanguages/main#1612 already resolves this issue.
