### ISSUE TITLE
Tags are missing

### ISSUE THREAD

**Issue by slozier** [IronLanguages/ironpython2#193]
Looks like all the version tags are missing from the repo.

**Comment by slide** [comment]
I'm not really sure that is a bug. New releases will have tags in this repo.

**Comment by slozier** [comment]
Not really a big deal, but it's still useful information to have. I was trying to do a bisect earlier to figure out what fixed an issue since the 2.7.7 release and since there were no tags I had to dig through the commits to find 2.7.7.

**Comment by slide** [comment]
Tags for releases were pushed.
