### ISSUE TITLE
Remove unnecessary features

### ISSUE THREAD

**Issue by slozier** [IronLanguages/ironpython2#200]
I did a quick survey of the feature tags and identified the ones which are widely supported (net40+ and netstandard1.1+). I propose we remove the conditional code for these features:
- FEATURE_APTCA
- FEATURE_COMPRESSION (this one appears limited to GZipStream)
- FEATURE_CUSTOM_MODIFIERS
- FEATURE_DEFAULT_PARAMETER_VALUE
- FEATURE_ENUM_NAMES_VALUES
- FEATURE_GETINVALIDFILENAMECHARS
- FEATURE_NUMERICS
- FEATURE_STOPWATCH
- FEATURE_TASKS

**Comment by slide** [comment]
Sounds great
