### ISSUE TITLE
Bad interaction between super and old-style classes

### ISSUE THREAD

**Issue by howardic** [IronLanguages/ironpython2#206]
super fails to work correctly (for `__init__` at least) when old style classes are parents. In this code:

```python
class aco(object):
  def __init__(self):
    print("init aco");
    super(aco, self).__init__();
    print("post super aco")

class x0:
  def foo():
    return

class x1(object):
  def bar():
    return

class two(x0, aco, x1):
  def __init__(self):
    print("init two");
    super(two, self).__init__();
    print("post super two")
```
when you created an object of class `two` you would expect it to call the `__init__` method from its parent `aco`. In fact, the super call seems to go nowhere and only the "init two" and "post super two" strings are printed. Note that when `x0` is turned into a new class the code works as expected. It's also okay when the order is changed to have `aco` precede `x0`.

We've traced the problem to some suspicious handling of old classes in Super.cs in the method below. Note the commented out line with +++ and the following line which contains the suggested fix. We are unfamiliar enough with the code nor do we have an extensive enough test suite to submit this as a pull request but can do so if requested.

```c#
        private bool TryLookupInBase(CodeContext context, PythonType pt, string name, object self, out object value) {
            PythonTypeSlot dts;

            if (pt.OldClass == null) {
                // new-style class, or reflected type, lookup slot
                if (pt.TryLookupSlot(context, name, out dts) && 
                    dts.TryGetValue(context, self, DescriptorContext, out value)) {
                    return true;
                }
            } else {
                // old-style class, lookup attribute                
                OldClass dt = pt.OldClass;

                if (
                    // +++ PythonOps.TryGetBoundAttr(context, dt, name, out value)
                    dt.TryLookupOneSlot(DescriptorContext, name, out value) // suggested fix
                    ) {
                    value = OldClass.GetOldStyleDescriptor(context, value, self, DescriptorContext);
                    return true;
                }
            }
            value = null;
            return false;
        }
 ```
Note: this problem turned up using the Facebook Marketing API via their supported Python SDK.

**Comment by slozier** [comment]
Thanks for the report. Created a PR based on the suggested fix and added a test.
