### ISSUE TITLE
Switch "Any CPU" build to be ipy.exe and create special build for 32-bit specific

### ISSUE THREAD

**Issue by slide** [IronLanguages/ironpython2#212]
Most people seem to end up using ipy64.exe, which isn't really a 64-bit build, it just uses Any CPU. We should make the default ipy.exe be Any CPU and create an ipy32.exe for 32-bit. Either that, or drop the 32-bit specific build for just an Any CPU build.

**Comment by slozier** [comment]
I would be fine with making the default AnyCPU. A reason for having a 32-bit version is to allow the use of 32-bit DLLs (via ctypes for example).

**Comment by slide** [comment]
This is done
