### ISSUE TITLE
MissingMethodException when calling CreateEngine()

### ISSUE THREAD

**Issue by waltdestler** [IronLanguages/ironpython2#221]
Hi, I'm developing an application that uses IronPython. For most of my users it's working great, but for a very small fraction of them the application throws this exception when trying to create the Python engine: `System.MissingMethodException: Methode nicht gefunden: "Microsoft.Scripting.Hosting.ScriptEngine IronPython.Hosting.Python.CreateEngine()".` (sorry for the German, a lot of my users are German)

This is using IronPython 2.7.7 and DLR 1.1.2 both from Nuget.

Is it possible there was a breaking change without a version bump which is causing an incompatible assembly to be loaded from the GAC?

Thanks!

**Comment by slide** [comment]
Are you sure they don't have a different version of the IronPython DLL's installed in the GAC?

**Comment by waltdestler** [comment]
Wouldn't that only be a problem if the version in the GAC had the same
version number as the DLL I distribute with my software?

**Comment by slide** [comment]
I think there was a version that had some versioning issues, I will look it up.

**Comment by waltdestler** [comment]
Did you figure anything out about the versioning issues? Thanks.

**Comment by slide** [comment]
No, I did not. Would it be possible to have your users enable fusion logging for assembly resolution?

**Comment by waltdestler** [comment]
@slide Okay, I finally found someone with this error who was able to turn on fusion logging. Here's a zip of the log files. (Unfortunately they appear to be in French, hopefully that's not a problem.)

[fusionlog.zip](https://github.com/IronLanguages/ironpython2/files/1249649/fusionlog.zip)

I don't know much about assembly binding, so maybe this is a non-issue, but I noticed that there are two log files for Microsoft.Scripting, one for version 1.1.1.22 and one for 1.1.2.22.  For the 1.1.1.22 version, the "calling assembly" is IronPython, and for the 1.1.2.22 version, the calling assembly is my own assembly.

**Comment by slide** [comment]
Yes, this is definitely a problem. There should be only one version (the same version as your app is using). So, somehow they have another version of Microsoft.Scripting on their computer and that is causing your issue.

**Comment by waltdestler** [comment]
@slide Okay, I have another clue. As an experiment, I tried redirecting 1.1.1.22 to 1.1.2.22 in my app.config and having the user test it:

```
<dependentAssembly>
	<assemblyIdentity name="Microsoft.Scripting" publicKeyToken="7f709c5b713576e1"/>
	<bindingRedirect oldVersion="1.1.1.22" newVersion="1.1.2.22"/>
</dependentAssembly>
```

While this did not fix the problem, it **did** produce a different error:
`Failed to load language 'IronPython 2.7.7rc1'`

The fact that it's trying to load 2.7.7rc1 is interesting, because my application uses 2.7.7 final, **not** rc1. I downloaded 2.7.7rc1 and looked at it with ILSpy, and indeed 2.7.7rc1 references Microsoft.Scripting 1.1.1.22.

So my hypothesis is that this user has or had another program on their computer that used 2.7.7rc1, causing it to be stored in the GAC. Since 2.7.7rc1 uses the same version number as 2.7.7 final (specifically 2.7.7.0), when my application tries to load IronPython, it actually loads 2.7.7rc1 from the GAC, hence the MissingMethodException.

Does this sound plausible? And if so, what I can do about it?

**Comment by slide** [comment]
Yes, this sounds very plausible. You could have them use gacutil to remove the older version.

**Comment by slozier** [comment]
Just for fun, I installed 2.7.7 RC1 (which by default puts Microsoft.Scripting in the GAC) and then tried to run my app which uses 2.7.7 final and I got the same failure.

**Comment by waltdestler** [comment]
Well, at least it's good to know the issue can be reproduced and it's not something weird I'm doing with my program.

I may be able to get this particular user to use gacutil since they seem pretty technically competent, but I don't think that's a generally viable solution for all users having this problem.

Is there any general solution I can do on my end besides "wait for a new version of IronPython"? (Any chance you could increment the version number just for the sake of busting the GAC?)

**Comment by slide** [comment]
The next release of IronPython should have a different version number (and all releases going forward). If you have an installer, you could try running gacutil in your installer. The other option would be to build the code yourself and package up your custom version, this is not a great idea though as your version could conflict with a future IronPython version.

**Comment by waltdestler** [comment]
My solution, which seems to work great, was simply to build IronPython myself and turn off strong-naming.

**Comment by slide** [comment]
Can we close this out then?

**Comment by waltdestler** [comment]
Yup, closing. I think the actionable takeaway here is simply to be mindful in the future about installing release candidates into the GAC without giving them a different version number than the final release.

**Comment by slide** [comment]
Yes, I completely agree

**Comment by slozier** [comment]
I thought the version numbers were different (1.1.1.22 and 1.1.2.22)?

**Comment by waltdestler** [comment]
@slozier The root problem was because two different IronPython assemblies (the release candidate and the final) have the same version number (2.7.7.0), and thus the release-candidate assembly was being loaded from the GAC instead of the intended assembly I bundle with my app.

I believe that the MissingMethodException is a symptom of that, due to my app being built against the final IronPython 2.7.7 release (which references Microsoft.Scripting 1.1.2.22) but was actually loading the release candidate at runtime (which references Microsoft.Scripting 1.1.1.22). The Python.CreateEngine() method returns a ScriptEngine object, which is a type in Microsoft.Scripting -- hence the MissingMethod exception when trying to call that method. (I think because it was looking for a method that returned a ScriptEngine 1.1.2.22, but the method in the actual loaded IronPython assembly returned a ScriptEngine 1.1.1.22.)
