### ISSUE TITLE
Investigate targeting netstandard2.0 instead of netcoreapp2.0

### ISSUE THREAD

**Issue by slozier** [IronLanguages/ironpython2#225]
We're currently targeting netcoreapp2.0 instead of netstandard2.0 because we're using some APIs which are not in netstandard2.0. However, we're supposedly able to use some of those APIs and still target netstandard2.0.

**Comment by slide** [comment]
Didn't we decide that this wouldn't be possible?

**Comment by slozier** [comment]
At the moment using Emit is not recommended, however it looks like they are reworking the package so that it may be possible it's the future.

**Comment by slozier** [comment]
Resolved by https://github.com/IronLanguages/ironpython2/pull/599
