### ISSUE TITLE
Force Use of TSLv1

### ISSUE THREAD

**Issue by gtalarico** [IronLanguages/ironpython2#227]
I am developing an API wrapper in Python and it works fine with CPython 2.7 and 3.

When I hit an https server from **IronPython**, I get the traceback below

    IOError: System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
       at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)

I analyzed the packages being sent by the different platforms and notice the only difference was that IronPython was the only one using TSL 1.0 Protocol, and CPython uses TSL 1.2 (see screenshot below)

I used the code below to force Cpython to use TSL 1.0 and got the exact same error, which confirms the issue is with the TSL protocol.
(The code allows me to change the HTTP adapter Protocol consistently)

The problem I am having is, the code below does not seem to have an effect on IronPython, and it continues to use TSL 1.0 on all requests regardless.

Could this be a an IronPython bug?

    import sys
    import platform
    print(platform.python_implementation())
    print(sys.version_info[0:2])
    
    import ssl
    import requests
    from requests.adapters import HTTPAdapter
    from requests.packages.urllib3.poolmanager import PoolManager
    
    if platform.python_implementation() == 'IronPython':
        print('Setting TSL Protocol')
        import System
        System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls12
    
    
    class ForceTLSV12Adapter(HTTPAdapter):
        """Require TLSv1 for the connection"""
        def init_poolmanager(self, connections, maxsize, block=False):
            # This method gets called when there's no proxy.
            self.poolmanager = PoolManager(
                num_pools=connections,
                maxsize=maxsize,
                block=block,
                ssl_version=ssl.PROTOCOL_TLSv1_2,
                # ssl_version=ssl.PROTOCOL_TLSv1,
            )
    
        def proxy_manager_for(self, proxy, **proxy_kwargs):
            # This method is called when there is a proxy.
            proxy_kwargs['ssl_version'] = ssl.PROTOCOL_TLSv1_2
            return super(ForceTLSV1Adapter, self).proxy_manager_for(proxy, **proxy_kwargs)
            
    s = requests.Session()
    s.mount('https://api.unleashedsoftware.com', ForceTLSV12Adapter())
    print(s.get("https://api.unleashedsoftware.com"))

![image](https://user-images.githubusercontent.com/9513968/28929867-199d4874-783f-11e7-8ce6-3c2c7e4c6295.png)

PS: I have also tried setting the system wide default protocol, but it does not seem to have any effect:
https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-a-default-secure-protocols-in

**Comment by slide** [comment]
This is one area that definitely needs some attention, we currently have a very basic implementation of the _ssl module. This is almost definitely a bug in IronPython.

**Comment by gtalarico** [comment]
Thanks @slide
Can you think if there any possible workarounds? 
This is a major blocker for the project I am working on.

**Comment by slide** [comment]
Do you need to stick with just Python libraries, or could you use .NET libraries as well? You could use the .NET SSL stuff directly instead of relying on the implementation in IronPython of the _ssl module.

**Comment by gtalarico** [comment]
I was avoiding it because I had just finished writing an api wrapper library and I was planning on using it with both Cpython and ironpython (when called from within a dotnet application) 

I solved it by making extending the main class so  that when 'platform.python_implementation()' is ironpython it uses WebRequest instead of python requests library
