### ISSUE TITLE
random.randint() returns incorrect distribution

### ISSUE THREAD

**Issue by jpmaterial** [IronLanguages/ironpython2#231]
The documentation says:

> random.randint(a, b) 
> Return a random integer N such that a <= N <= b.
> 

However, when I test this with a number of values, I get a skewed distribution.

This is my test script:

```
#!/usr/bin/ipy64

import random, sys

if len(sys.argv)==1:
	random.seed()
else:
	random.seed(int(sys.argv[1]))

def histogramm(r,a,b):
	h=dict()
	for i in range(r):
		ri=random.randint(a,b)
		if ri not in h:
			h[ri]=1
		else:
			h[ri]+=1
	print 'histogramm for randint(%i,%i)'%(a,b)
	for k in sorted(h.keys()):
		print '  %8i:%8.0f%%'%(k,h[k]*100.0/r)

num_samples=1000*1000
histogramm(num_samples,1,3)
histogramm(num_samples,1,4)
histogramm(num_samples,0,3)
histogramm(num_samples,-3,-1)
histogramm(num_samples,1,11)
histogramm(num_samples,1,21)
histogramm(num_samples,-10,11)
```

This is my output:

```
histogramm for randint(1,3)
         1:      67%
         2:      33%
histogramm for randint(1,4)
         1:      50%
         2:      50%
histogramm for randint(0,3)
         0:      50%
         1:      50%
histogramm for randint(-3,-1)
        -3:      67%
        -2:      33%
histogramm for randint(1,11)
         1:      18%
         2:      18%
         3:      18%
         4:      18%
         5:      18%
         6:       9%
histogramm for randint(1,21)
         1:      10%
         2:       9%
         3:      10%
         4:      10%
         5:      10%
         6:       9%
         7:      10%
         8:      10%
         9:      10%
        10:       9%
        11:       5%
histogramm for randint(-10,11)
       -10:       9%
        -9:       9%
        -8:       9%
        -7:       9%
        -6:       9%
        -5:       9%
        -4:       9%
        -3:       9%
        -2:       9%
        -1:       9%
         0:       9%
```
It does not really depend on the used seed.
I'm on Windows 10. These are my versions:

IronPython 2.7.7 (2.7.7.0) on .NET 4.0.30319.42000 (64-bit)

**Comment by slide** [comment]
I tested this with my local build of IronPython2 (latest master) and I see similar results between CPython2.7 and IronPython2. It's possible that the version you have doesn't have some of the updates for _random that was done over the past year or so.

**Comment by jpmaterial** [comment]
That sounds good. When will the next release be?

**Comment by slide** [comment]
As soon as possible. I am working on the release updates after we moved the code from the old repository.

**Comment by slozier** [comment]
This one was fixed with IronLanguages/main#1584

**Comment by jpmaterial** [comment]
Note for anyone who needs to work around this issue in IronPython 2.7.7 (and possibly earlier): Don't call randint() (and randrange(), random(), ...) from random directly, but generate a Wichmann-Hill RNG.

So instead of


```
...
import random
random.seed(seed)
ri=random.randint(a,b)
```

just do

```
...
import random
rng=random.WichmannHill(seed)
ri=rng.randint(a,b)
```

That will produce a uniform distribution.

**Comment by slide** [comment]
Thanks for the info!
