### ISSUE TITLE
IronPython 2.7.7: No data is available for encoding 0

### ISSUE THREAD

**Issue by QuAzI** [IronLanguages/ironpython2#234]
I try to use python modules from C# project but `Python.CreateEngine()` throws exception
```
System.Reflection.TargetInvocationException: 'Failed to load language 'IronPython 2.7.7': No data is available for encoding 0. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.'
```

TargetFramework: netcoreapp2.0
Visual Studio 2017 CE

Installed packages
```
<PackageReference Include="IronPython" Version="2.7.7" />
<PackageReference Include="IronPython.Interpreter" Version="2.7.4" />
<PackageReference Include="IronPython.StdLib" Version="2.7.7" />
<PackageReference Include="System.CodeDom" Version="4.4.0" />
<PackageReference Include="System.Text.Encoding.CodePages" Version="4.4.0" />
```

**Comment by slozier** [comment]
Sounds like you're trying to use it in a .NET Core app? We haven't released a .NET Core package yet.

**Comment by QuAzI** [comment]
Yes, .NET Core. Is support in plans? There are some approximate date?

**Comment by slozier** [comment]
Yes, we plan to support .NET Core (in fact the code is already merged in this repo if you wanted to build it yourself). We don't have an approximate date at this point but hopefully before the end of the month?

**Comment by slide** [comment]
There is a beta release with .net core 2.0 support at https://ci.appveyor.com/project/AlexEarl/ironpython2/build/2.7.8.1-397/artifacts.

**Comment by Quanghoster** [comment]
Hi - I've installed the IronPython v2.7.8-beta1 from nu-get and am getting the following error when I try to install the same version of StdLib... 

Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to resolve dependencies. 'IronPython 2.7.8-beta1' is not compatible with 'IronPython.StdLib 2.7.8-beta1 constraint: IronPython (>= 2.7.8 && < 3.0.0)'.			0

**Comment by slide** [comment]
@Quanghoster Ok, this should definitely be resolved when the final version is released. I'll also look into how to specify the versions so it works with pre-releases.

**Comment by slide** [comment]
Closing this out as 2.7.7 doesn't have .net core support
