### ISSUE TITLE
I can not compile by myself , is there have a self-building manual?

### ISSUE THREAD

**Issue by danperor** [IronLanguages/ironpython2#237]
I recently encountered a serious problem in the use of the code, want to use the code to build self, but the downloaded code can not compile

**Comment by slozier** [comment]
There's no "self-build manual" at the moment. You should use `make.cmd` on Windows or the `Makefile` on Linux (to build with Mono). Note that Visual Studio 2017 15.3 is required to build on Windows.

**Comment by slide** [comment]
Please provide more information on what is going on with your build.

**Comment by slide** [comment]
See https://github.com/IronLanguages/ironpython2/blob/master/Documentation/building.md
