### ISSUE TITLE
IronPython: Is it possible to install packages from a wheel file?

### ISSUE THREAD

**Issue by zvacha** [IronLanguages/ironpython2#243]
I am trying to do the following:
c:\Users\default>ipy -X:FullFrames -m pip install wheel c:\users\default\Downloads\cffi-1.11.0-cp27-cp27m-win32.whl
cffi-1.11.0-cp27-cp27m-win32.whl is not a supported wheel on this platform
I get the above error. I have tried different packages. 
Doesn't IronPython doesn't support installation from wheel or am I doing something wrong?
Any ideas/comments?

**Comment by slide** [comment]
Well, cffi won't be supported anyway because it uses a native (C based) extension. You are probably getting the error because the wheel is specifically for the 'win32', but the platform for IronPython is 'cli'. Platform specific wheels won't work on IronPython.

**Comment by zvacha** [comment]
Thank you!!
Let me try with the cli platform

**Comment by zvacha** [comment]
I don't see any packages for cli platform in Pypi. Am I missing anything?

**Comment by slide** [comment]
Sorry, I misled you perchance. I wasn't saying that there were packages available for CLI, I was saying that the win32 package will not install on IronPython because the platform is cli not win32. There are not any cli specific packages on pypi. Can you use ctypes?

**Comment by zvacha** [comment]
I see, thanks for the help. 
I believe I can use ctypes. What I am really trying to do is install the PyNACl package.

**Comment by slide** [comment]
PyNACl is a C based extension, it will no work on IronPython.
