### ISSUE TITLE
IntelliSense works with x86 DLL but not x64 version

### ISSUE THREAD

**Issue by MatthewJonesCo** [IronLanguages/ironpython2#279]
I am working with VS Enterprise 2017 and IronPython 2.7.  I would like to reference various .NET assemblies that are x64.  IntelliSense will work fine against an x64/x86 referenced .NET assembly in a 64/32-bit interactive environment.  IntelliSense in the editor will work fine with an x86 version of the assembly.  However, IntelliSense in the editor will not work with an x64 version of the assembly.  Perhaps a relationship to VS running as 32-bit?

I would appreciate any ideas to enable IntelliSense to work for x64 assemblies.  I've attached the project I was using to test the scenarios.  Thanks!

[IronPythonIntellisenseTesting.zip](https://github.com/IronLanguages/ironpython2/files/1511654/IronPythonIntellisenseTesting.zip)

**Comment by slide** [comment]
It looks like this is related to Python Tools for Visual Studio. You'll want to file this issue over on their github location at https://github.com/microsoft/PTVS.
