### ISSUE TITLE
netstandard support

### ISSUE THREAD

**Issue by hanabi1224** [IronLanguages/ironpython2#284]
Is there any particular reason for not publishing for netstandard?
I tested with a simple hello world program in a netstandard2.0 lib and it worked, but it's annoying to have the warning 'Package 'IronPython 2.7.8-beta1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.'

**Comment by slide** [comment]
We have an issue open for this already. See #225

**Comment by slide** [comment]
Also, just as an FYI, there are some things that don't work under netstandard that need to be looked at before we can target it directly
