### ISSUE TITLE
Move IronLanguages/main to IronLanguages/ironpython2?

### ISSUE THREAD

**Issue by slide** [IronLanguages/ironpython2#29]
_From @slozier on May 17, 2017 19:30_

As part of #1652 #1653 and #1654 I would suggest forking IronLanguages/main into IronLanguages/ironpython2 where we could:
- rework the file hierarchy into something matching the IronLanguages/ironpython3 repo
- rename the ipy-2.7-maint branch to master (and drop master)

_Copied from original issue: IronLanguages/main#1655_

**Comment by slide** [comment]
Fixed!

**Comment by michaelblyons** [comment]
Do you want to migrate the Wiki pages, too? (And if so, the link in README.md should be updated to match.)

**Comment by slozier** [comment]
Yes we should probably migrate most (excluding IronRuby stuff) of the wiki over.
