### ISSUE TITLE
Call to ironpython from standard python

### ISSUE THREAD

**Issue by sushantPythonCactus** [IronLanguages/ironpython2#308]
Am having an django project which is all set in production. But for requirement, have used pythoncom32 to connect to Microsoft  but now I want to use ironPython, and use 'Microsoft.Office.Interop.Word' ? I see this
https://stackoverflow.com/questions/27800327/call-ironpython-from-standard-python
I see lots of resource for accessing python in .NET but not vice versa. I know this is not an issue but tired of stackoverflow and reddit, no replies. M hoping help here.

**Comment by slide** [comment]
Please use the mailing list for questions, users@ironpython.groups.io
