### ISSUE TITLE
platform.system is returning cli on Windows

### ISSUE THREAD

**Issue by slozier** [IronLanguages/ironpython2#311]
`platform.system()` is returning `cli` on Windows but `Darwin` on macOS. My take on it is that it should probably return `Windows` on Windows.

For:
- Gives a (non .NET) API which can give OS information
- Makes it easier to detect macOS vs Linux (both of these have `os.name == "posix"`)

Against:
- Jython returns the Java runtime information instead of OS information.

**Comment by slide** [comment]
I guess the question would be is there any code that is vital that looks at platform.system() instead of os.name or something?

**Comment by slozier** [comment]
Seems like it's barely used anywhere and as far as I know the fact that it returns cli isn't used in the codebase.

**Comment by elitest** [comment]
If it was running on Mono on Ubuntu vs .Net on Windows, would it actually have any way to distinguish?

**Comment by slide** [comment]
@elitest os.name = 'win32' on windows and 'posix' on Linux and macOS. So, we know at the point in platform.py that it checks, we can assume 'cli' means Windows. Linux and macOS have a os.uname implementation, so they will return the expected values.
