### ISSUE TITLE
IronPython 2.7.7 is not compatible with DynamicLanguageRuntime 1.2.0.100.l

### ISSUE THREAD

**Issue by rabrahamOpti** [IronLanguages/ironpython2#317]
The following C# Console application project code, using IronPython 2.7.7, throws an exception when the project is referencing DynamicLanguageRuntime 1.2.0.100.l. It works just fine when the project is referencing DynamicLanguageRuntime 1.1.2.

    using IronPython.Hosting;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;    

    namespace TestApp
    {
    	class Program
    	{
    		static void Main(string[] args)
    		{
    			var options = new Dictionary<string, object>();
    			options["Frames"] = true;
    			options["FullFrames"] = true;
    			var engine = Python.CreateEngine(options);
    			string pyscript = @"";    

    			var script = engine.CreateScriptSourceFromString(pyscript);
    			var paths = engine.GetSearchPaths();
    		}
    	}
    }

When using DynamicLanguageRuntime 1.2.0.100.l, the exception that's thrown is:

    An unhandled exception of type 'System.Reflection.TargetInvocationException' occurred in Microsoft.Scripting.dll

Whose inner exception reads:

    Could not load type 'System.TypeExtensions' from assembly 'Microsoft.Scripting, Version=1.2.0.0, Culture=neutral

Inner Exception Source:

    IronPython

Inner Exception Stack Trace:

    at IronPython.Runtime.PythonContext.GetInitialPrefix()
    at IronPython.Runtime.PythonContext..ctor(ScriptDomainManager manager, IDictionary`2 options)

[The Nuget page](https://www.nuget.org/packages/IronPython) claims IronPython 2.7.7 should be compatible with any version of DynamicLanguageRuntime >= 1.1.2, so there's either a bug, or the dependency constraint should be updated. Again, the exception is not thrown when the project is using DynamicLanguageRuntime 1.1.2.

**Comment by slide** [comment]
The dependency in 2.7.7 is incorrect. There is not a way to update the nuget package for 2.7.7, nuget doesn't allow this. This is a known issue. The recommendation would be to add a reference to  DynamicLanguageRuntime 1.1.2 and then add a reference to IronPython 2.7.7.

**Comment by joelharkes** [comment]
I'm having the same issue,
But only if iron python is also installed on my computer.

If i simply uninstall iron python it seems to work. downgrading to DynamicLanguageRuntime 1.1.2 did not fix this for me.

**Comment by joelharkes** [comment]
for me its working with:
```
<package id="DynamicLanguageRuntime" version="1.2.0" targetFramework="net452" />
<package id="IronPython" version="2.7.7" targetFramework="net452" />
``` 
No Iron python installed on windows.

IPY installed i get error:
```

inner: Failed to load language 'IronPython 2.7.7': Kan type System.TypeExtensions niet laden vanuit assembly Microsoft.Scripting, Version=1.2.0.0, Culture=neutral, PublicKeyToken=7f709c5b713576e1.
```

hadding same kind of issues on IPY 2.7.3 before.

Trying to find away around it, havent found it so far. il give an update if/when i found a solution.

if somebody has a solution this would be greatly appreciated.

**Comment by joelharkes** [comment]
@slide seemed to have been right, downgrading nuget and removing runtime app.config (that was still redirecting to 1.2.0) fixed this and also fixed runtime python errors i was getting.

**Comment by pankon** [comment]
Adding package from .nuget\packages\dynamiclanguageruntime\1.1.2\lib\Net40 worked for me
