### ISSUE TITLE
Reorganize bin directory structure

### ISSUE THREAD

**Issue by slozier** [IronLanguages/ironpython2#32]
As prep work for .NET Core support it would be nice to update the bin folder to use the following structure:
/bin/{Flavor}/{TFM}

For example:
/bin/Release/net40
/bin/Release/net45
/bin/Release/netcoreapp2.0
/bin/Debug/net45

Here's the list of TFMs:
https://docs.microsoft.com/en-us/nuget/schema/target-frameworks

**Comment by slide** [comment]
This has been implemented.
