### ISSUE TITLE
argtypes member behaves incorrectly in ctypes

### ISSUE THREAD

**Issue by MrElusive** [IronLanguages/ironpython2#332]
Consider the following C++ code that compiles to a small library called test_lib.dll:
```cpp
#include <iostream>

#if defined(_WIN32)
  #define EXPORT __declspec(dllexport)
#else
  #define EXPORT
#endif

extern "C" 
{
    void EXPORT print_string_buffer(const char* buffer) 
    {
        std::cout << buffer << std::endl;
    }
    
    void EXPORT print_double_array(const double* array, size_t size) 
    {
        if (size == 0)
        {
            std::cout << "[]" << std::endl;
        }
        else
        {
            std::cout << "[" << array[0];
            for (size_t i = 1; i < size; i++)
            {                
                std::cout << ", " << array[i];
            }
            std::cout << "]" << std::endl;
        }
        
    }
}
```

Now consider the following two tests that call into test_lib through ctypes:
```python
import ctypes

test_lib = ctypes.CDLL("test_lib")

def test_1():    
    # test_lib.print_string_buffer.argtypes = [ctypes.c_char_p] # uncommenting this line fixes the problem
    test_lib.print_string_buffer(ctypes.create_string_buffer("1".encode()))
    
    # raises exception: _ctypes.ArgumentError: expected c_char_Array_2, got c_char_Array_3
    test_lib.print_string_buffer(ctypes.create_string_buffer("11".encode()))


def test_2():
    test_lib.print_double_array.argtypes = [ctypes.POINTER(ctypes.c_double)] # commenting this line fixes the problem
    double_array = (ctypes.c_double * 3)()
    double_array[0] = 0.1
    double_array[1] = 1.1
    double_array[2] = 2.1
    
    # raises exception: _ctypes.ArgumentError: expected c_double, got c_double_Array_3
    test_lib.print_double_array(double_array, len(double_array))
    
test_1() 
#test_2()
```

Both of these tests run fine in Python (2 and 3). However, they both fail in IronPython unless the appropriate lines are commented or uncommented as described in the tests.

For test_1, IronPython appears to be caching the argtype of the last call to print_string_buffer. If I switch the lines so that "11" prints first and "1" prints second, then the error becomes "_ctypes.ArgumentError: expected **c_char_Array_3, got c_char_Array_2**" However, the value of `print_string_buffer.argtypes` in between the two calls still shows as `None` when I print it to the console.

For test_2, IronPython is happy if I pass a single double to the function using `ctypes.byref()`, but not when I pass an array.

A google search reveals that these issues have been documented [here](https://codebright.wordpress.com/2010/06/23/strange-behaviour-using-ctypes-in-ironpython/)

**Comment by slide** [comment]
Thanks for the in-depth report! We'll look into this soon.

**Comment by slide** [comment]
So, the issue here is that IronPython is doing a type check prior to marshalling the data, which I am not sure CPython does. If you look here: https://github.com/IronLanguages/ironpython2/blob/master/Src/IronPython.Modules/ModuleOps.cs#L104 There is a check of `res.NativeType` against `type`. In this case, the `type` argument is `c_char_Array_2` and `res.NativeType` is `c_char_Array_3`. I need to study the C Python ctypes code a bit more to see how they handle situations like this. If I comment out the type check, the code behaves the same as C Python, but I am not sure if that is the correct solution yet.
