### ISSUE TITLE
IronPython is mishandling the bytes literal

### ISSUE THREAD

**Issue by DenisBozic** [IronLanguages/ironpython2#333]
In https://docs.python.org/2/reference/lexical_analysis.html#string-literals it states:
_A prefix of 'b' or 'B' is ignored in Python 2; it indicates that the literal should become a bytes literal in Python 3 (e.g. when code is automatically converted with 2to3)_

If I run this:
 **_print repr(b'2433333')_**
I see:
**_b'2433333'_**

This impacts on libraries like shapely

**Comment by slozier** [comment]
In Python 2 `bytes == str` which is why the prefix is ignored. However, in IronPython 2 `str == unicode` so the `b` prefix cannot be ignored.
