### ISSUE TITLE
Something is wrong with Python.CreateEngine(); in dotnet core.

### ISSUE THREAD

**Issue by mohsens22** [IronLanguages/ironpython2#344]
I'm trying t add this piece of code in my dotnet Core application via `IronPyhon` package.
`var py = Python.CreateEngine();`
But the fact is that It's complaining about `Microsoft.Scripting` namespace. I'm trying to run python scripts into my C# code.
Error: The type 'ScriptEngine' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Scripting, Version=1.2.0.0, Culture=neutral, PublicKeyToken=7f709c5b713576e1'.

**Comment by slide** [comment]
Did you add a reference to Microsoft.Scripting?

**Comment by mohsens22** [comment]
Thanks a million @slozier and @slide .
the problem was the missing DynamicLanguageRuntime package.

**Comment by slide** [comment]
Maybe I should do a release with that fix so more people are bitten by the issue.

**Comment by mohsens22** [comment]
@slide Sure do it. Unless more people will get into trouble. The'll stop using your solution or they make silly issues like this one.

**Comment by slide** [comment]
The release to Nuget was done

**Comment by damlaYasarr** [comment]
@Mohsens22  hi! I have the same issue, I installed DynamicLanguageRuntime package but still the same problem.. 
 var engine = Python.CreateEngine(); here is not work..

**Comment by michaelchadfleming** [comment]
Try:

var engine = IronPython.Hosting.Python.CreateEngine();
