### ISSUE TITLE
unicodedata.east_asian_width not works well

### ISSUE THREAD

**Issue by xalley** [IronLanguages/ironpython2#357]
I am using a module name terminaltables, it works well in cpython2 and cpython3 but not ironpython2, and I found that problem is `unicodedata.east_asian_width`

cpython2
```
>> unicodedata.east_asian_width(u'中')
'W'
```

ironpython2
```
>> unicodedata.east_asian_width(u'中')
''
```

I try to read [unicodedata.cs](https://github.com/IronLanguages/ironpython2/blob/40f51b92f8294bb901d29738707103f92fe19c87/Src/IronPython/Modules/unicodedata.cs), it seems that variable `ranges` never used, is this the bug?

could you please help me fix it? thanks.

**Comment by slozier** [comment]
@xalley Can you try the build at https://ci.appveyor.com/project/AlexEarl/ironpython2/build/2.7.8.1-514/artifacts to see if it resolves your issue?

**Comment by xalley** [comment]
@slozier It resolves my issue. Thank you very much.
