### ISSUE TITLE
`ElementTree.iterparse` not implemented

### ISSUE THREAD

**Issue by pekkaklarck** [IronLanguages/ironpython2#370]
Our project needs `ElementTree.iterparse` to parse large XML files memory efficiently. Unfortunately it is not implemented in IronPython:

```python
IronPython 2.7.8 (2.7.8.0) on .NET 4.0.30319.42000 (64-bit)
Type "help", "copyright", "credits" or "license" for more information.
>>> from xml.etree import ElementTree as ET
>>> from StringIO import StringIO
>>> ET.iterparse(StringIO('<root/>'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Program Files\IronPython 2.7\Lib\xml\etree\ElementTree.py", line 1198, in iterparse
NotImplementedError: iterparse is not supported on IronPython. (CP #31923)
>>>
```

We have instructed our users to install [ElementTree 1.2.7 preview release from 2007](http://effbot.org/downloads/#elementtree) and it seems to work fine, but having such an extra dependency that cannot even be pip-installed is highly annoying. Incorporating the fixes from the aforementioned ElementTree version into IronPython itself would be great.

**Comment by slide** [comment]
Do you have a test XML I could use to test a minimal implementation of pyexpat in IronPython?
