### ISSUE TITLE
`UnicodeDecodeError` has no error message

### ISSUE THREAD

**Issue by pekkaklarck** [IronLanguages/ironpython2#375]
When decoding bytes with bad encoding, the resulting `UnicodeDecodeError` has no error message:

```
E:\>ipy -V
IronPython 2.7.8 2.7.8.0 on .NET 4.0.30319.42000
E:\>ipy -c "b'\xe4'.decode('ASCII')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
UnicodeDecodeError
```

With CPython the message exists and also earlier IronPython versions had it.

```
E:\>python -c "b'\xe4'.decode('ASCII')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)
```

Error message used to be better in earlier IronPython versions. Because exception type is correct, this isn't too severe.

**Comment by slide** [comment]
Do you know what version of IronPython had a better message? I'd like to look at the code for that version if possible.

**Comment by slide** [comment]
Yeah, it looks like they just printed the default ToString of BaseException, which is to print the args tuple. We could pass the exception .Message property as the `reason` which would then be printed out, but it won't match C Python's error messages. It looks like we don't have access to which encoding had the issue, we can get the byte and index info though.

It would look like this for the example code.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
UnicodeDecodeError: Unable to translate bytes [E4] at index 0 from specified code page to Unicode.
```

**Comment by pekkaklarck** [comment]
I don't remember which version had a better message but I'm sure there was some kind of a message. I don't think the message needs to match CPython message exactly.

**Comment by slozier** [comment]
@slide Don't we have the encoding name in DoDecode? We could intercept the exception and add it (or throw a new one). Or is this thoring from somewhere else?
