### ISSUE TITLE
`*.exe` files are not created when installing packages

### ISSUE THREAD

**Issue by pekkaklarck** [IronLanguages/ironpython2#380]
We recently changed our project's installation to use [setuptools entry-points](http://setuptools.readthedocs.io/en/latest/setuptools.html#automatic-script-creation) to automatically create start-up scripts, most importantly to get `*.exe` files on Windows (robotframework/robotframework#2415). Unfortunately the `*.exe` files aren't created when using IronPython 2.7.8.

**Comment by pekkaklarck** [comment]
We don't yet have a release with the new installation system available, but you can test it by running `ipy -m pip install https://github.com/robotframework/robotframework/archive/master.zip`. Instead of the `robot.exe` file I get with CPython, I get `robot` file with this content:

```python
#!c:Program FilesIronPython 2.7ipy.exe
# EASY-INSTALL-ENTRY-SCRIPT: 'robotframework==3.1.0.dev1','console_scripts','robot'
__requires__ = 'robotframework==3.1.0.dev1'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('robotframework==3.1.0.dev1', 'console_scripts', 'robot')()
    )
```

**Comment by slide** [comment]
I'm looking into this, I have to understand setuptools a bit better before I can get something going.

**Comment by slide** [comment]
So, I just tried this with easy_install and pip themselves and the correct .exe files are generated for easy_install and pip. I am not sure what is different for their setup compared to yours, so I will continue looking into it. There are a couple of things I had to cleanup in the bundled setuptools and pip whl files to have the launchers work correctly, so I will create a PR for those soon.
