### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by terrybogero** [IronLanguages/ironpython2#384]
### Prerequisites
System specification:
linux-arm(fedora 22)
.net core 2.0.4
Ironpython 2.7.8.1 (Python 2.7.10 )

### Description
my app run in linux-arm(Fedora22 .NET Core2.0.4) is failing.
in this step: MyCompiledCode.Execute(MyScriptScope);
throw error: Segmentation fault (core dumped)

but run in win64 and ubuntu.16.04-x64 is well.

please help me and give me some advice.
thanks

**Comment by slide** [comment]
If your code is working on x86, this sounds like an issue with dotnet core on arm. There really isn't much we can help with with the minimal information you have provided. You probably want to use gdb or something to find out what is causing the segfault.
