### ISSUE TITLE
IronPython issue installing PIP

### ISSUE THREAD

**Issue by slide** [IronLanguages/ironpython2#42]
_From @ahmedbodi on January 22, 2017 2:11_

This is the error i get when trying to install pip. running on Windows 10. Latest Release 2.7.7. 64 Bit Machine
```
C:\Program Files (x86)\IronPython 2.7>"C:\\Program Files (x86)\\IronPython 2.7\\ipy64.exe" -X:Frames  -m ensurepip
Ignoring indexes: https://pypi.python.org/simple
Collecting setuptools

Process is terminated due to StackOverflowException.```

_Copied from original issue: IronLanguages/main#1570_

**Comment by slide** [comment]
_From @slozier on January 22, 2017 11:38_

I confirm that running `ensurepip` with `ipy64` gives a `StackOverflowException`.

As a workaround I believe you can run it with the 32-bit `ipy` and it will work (and do the same thing). Note that you need to run it with an admin console since it installs files in your program files folder.

**Comment by slide** [comment]
_From @ahmedbodi on January 22, 2017 12:53_

with ipy it gives the same error

**Comment by slide** [comment]
_From @ahmedbodi on January 22, 2017 12:54_

```
C:\Program Files (x86)\IronPython 2.7>ipy.exe -X:Frames -m ensurepip
Ignoring indexes: https://pypi.python.org/simple
Collecting setuptools

Process is terminated due to StackOverflowException.

C:\Program Files (x86)\IronPython 2.7>
```

**Comment by slide** [comment]
_From @slozier on January 23, 2017 22:5_

I managed to reproduce with the following (while running `ipy64` - still works fine for me in 32-bit). Although I can't seem to get it to fail when the debugger is attached.
```
import mimetypes
print(mimetypes.guess_type(r"https://docs.python.org/2/library/mimetypes.html"))
```

Another possible workaround you could try is to try `ipy.exe -X:Frames -X:Debug -m ensurepip`.

**Comment by slide** [comment]
_From @ahmedbodi on January 25, 2017 20:15_

Okay now this is weird.

On my laptop, i was using a local account which has administrator privs. however it is also connected to a domain. Just now i've logged into the domain administrator account and tried it and it works fine. Any idea why?

**Comment by slide** [comment]
_From @jump3r34 on January 25, 2017 20:32_

I didn't have time to mess with IronPython for hours to get it working, sorry guys.

I am proficient enough with C# and Python individually that the headache was not worth the work.  Both of my windows laptops and office machine was having different errors, however, python2.7 and python3.5 and 3.6 work flawlessly on them and my Macbook.  

I was really using it to get a few complicated db functions I had already reflected with SQLalchemy in a WPF app for our sales guys, but I just put it in a django app already.  

I am staying subscribed to this thread because if they ever got Python3 on IronPython - it would make some of the things I do - much much quicker. Also, if I get some time in the next few weeks I am going to actually crack open the VS2015 full debugging environment and find what is throwing that error so it can help a lot of people online.

**Comment by slide** [comment]
_From @ahmedbodi on January 25, 2017 20:42_

i now cant install anything because i get a sys_getframe error. ive tried with -X:Frames or X:FullFrames

**Comment by slozier** [comment]
Closing this one since the StackOverflowError from the original issue is the same issue as https://github.com/IronLanguages/ironpython2/issues/40.
