### ISSUE TITLE
Change meaning of Condition in test case files

### ISSUE THREAD

**Issue by slozier** [IronLanguages/ironpython2#421]
Currently the `Condition` in test case files is the "run condition" this is somewhat confusing when combined with the `Reason`. It seems to me like `Condition` should be the "skip condition". For example:
```
[test_argparse]
Condition='$(OS)' != 'Unix'
Reason=This fails on Linux for some reason, needs debug
```
would become
```
[test_argparse]
Condition='$(OS)' == 'Unix'
Reason=This fails on Linux for some reason, needs debug
```

**Comment by slide** [comment]
I'm not sure I agree with this. Maybe we can just change to RunCondition instead of just Condition? Making it a skip condition would be confusing to me.

**Comment by slozier** [comment]
That would probably be fine as well.
