### ISSUE TITLE
Process is terminated due to StackOverflowException when appending to much lists

### ISSUE THREAD

**Issue by IUserNew** [IronLanguages/ironpython2#422]
Executing following code in IronPython 2.7 results in  Process is terminated due to StackOverflowException. Tried same in Python 2.7 but works fast and fine. Means, something is wrong with ipy. Can anyone support.

mylist1 = [0x20, 0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20]
mylist2 = [0x20, 0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20]
mylist3 = [0x20, 0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20]
mylist4 = [0x20, 0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20]

mylist = mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + \
         mylist1 + mylist2 + mylist3 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4 + mylist4

**Comment by IUserNew** [comment]
No one out there to fix this issue?

**Comment by slide** [comment]
We have about two people right now that have some time to work on things. We are doing the best we can, but if you want to see it fixed sooner, it may help to try and root cause the issue and create a PR

**Comment by slide** [comment]
I at least looked at this in the debugger, it looks like it's having an issue in BinaryExpression#ConstantFold. Since there are so many recursive items in the BinaryExpression, the ConstantFolding gets the StackOverflowException. I am not sure the best way to fix this right now. You may need to re-architect your code for now.

**Comment by slozier** [comment]
Duplicate of https://github.com/IronLanguages/ironpython2/issues/110
