### ISSUE TITLE
Installer does not seem to know which direction is up

### ISSUE THREAD

**Issue by fossum** [IronLanguages/ironpython2#427]
### Description

When trying to upgrade IronPython, the installer says 2.7.5 is later than 2.7.8.

![ipy_install_error](https://user-images.githubusercontent.com/448582/41737237-38293c5c-757e-11e8-8772-31dcc6a478c6.PNG)

### Steps to Reproduce

1. Have IronPython 2.7.5.0 installed.
2. Grab latest msi installer.
3. Execute installer

**Expected behavior:** Installer should proceed normally.

**Actual behavior:** Installer fails with version error.

### Versions

2.7.5.0

**Comment by slide** [comment]
This is a known issue because of the way that the installer for pre 2.7.8 was done. There is no fix for this and won't be. You must uninstall previous versions before installing 2.7.8.
