### ISSUE TITLE
BaseHTTPServer deadlock

### ISSUE THREAD

**Issue by tarlano** [IronLanguages/ironpython2#434]
I am running IronPython.2.7.8 using the ipy.sh script in the netcoreapp2.0 dir on Darwin Kernel Version 17.6.0

### Description

The following example from the Python Standard Library book fails:

http://effbot.org/librarybook/basehttpserver.htm

### Steps to Reproduce

In terminal 0:

computer:~/Downloads/IronPython.2.7.8/netcoreapp2.0$ wget http://effbot.org/librarybook/basehttpserver/basehttpserver-example-1.py
--2018-07-01 14:05:19--  http://effbot.org/librarybook/basehttpserver/basehttpserver-example-1.py
Resolving effbot.org (effbot.org)... 207.38.86.243
Connecting to effbot.org (effbot.org)|207.38.86.243|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/plain]
Saving to: ‘basehttpserver-example-1.py’

basehttpserver-example-1.     [ <=>                               ]   1.23K  --.-KB/s    in 0s      

2018-07-01 14:05:20 (35.5 MB/s) - ‘basehttpserver-example-1.py’ saved [1264]

computer:~/Downloads/IronPython.2.7.8/netcoreapp2.0$ ./ipy.sh basehttpserver-example-1.py

**Expected behavior:** 

In terminal 1:

computer:~$ curl -s http://localhost:8000/
<html>
<body>
<p>Today's quote: 
<i>Albatross! Albatross! Albatross!</i>
</body>
</html>

**Actual behavior:**

In terminal 1:

computer:~$ curl -s http:localhost:8000/

<Deadlock>

### Versions

computer:~/Downloads/IronPython.2.7.8/netcoreapp2.0$ ./ipy.sh -V
IronPython 2.7.8 2.7.8.0 on .NET 4.0.30319.42000

**Comment by slozier** [comment]
Good news/bad news. Good news is I tried with the latest bits and it doesn't deadlock. Bad news is that instead it crashed and I had to tweak `socket.py` to get it working.
