### ISSUE TITLE
ctypes tests failing in 32-bit

### ISSUE THREAD

**Issue by slozier** [IronLanguages/ironpython2#436]
The following ctypes tests are failing in 32-bit mode:
test_as_parameter
test_bitfields
test_callbacks
test_cfuncs
test_checkretval
test_funcptr
test_functions
test_libc
test_loading
test_returnfuncptrs
test_stringptr
test_values
test_win32

**Comment by slide** [comment]
We should add a flag to make.ps1 to run in 32bit mode and once we get the CI we can run them too
