### ISSUE TITLE
Poor performance in WeakRef class after many calls

### ISSUE THREAD

**Issue by tinyg** [IronLanguages/ironpython2#437]
### Description

If i run the code:

```
from collections import Iterable
from System.Diagnostics import Stopwatch;

s = Stopwatch()
for i in range(150000):
	s.Start()
	isinstance(1, Iterable)
	s.Stop();
	if i % 1000 == 0:
		print(str(i) + ": " + str(s.ElapsedMilliseconds))
	
	s.Reset()
```

then after a certain point (for me approx. 60000 iterations) all subsequent calls to the function take a very long time (0 ms before, 45ms after)

Looking at the runtime of the slow version in dotTrace, i can see that its coming from WeakRef.@ref.__new__. 

In the first (working) runs, i can see that the __new__ function is called ~63000 times taking a total of 119ms and it called GetWeakRef approximately the same number of times taking 30ms

In the bad (slow) runs, i can see that the __new__ function is called 64 times taking a total of 6500ms and it called GetWeakRef ~7,800,000 times taking a total of ~3200ms. It also calls GetHandlerCount and GetHandlerCallback for similar counts and times.

### Steps to Reproduce

1. Save code to a file (eg: test.py)
2. Run ipy test.py
3. observe that, after a certain point, the time taken drastically increases

**Expected behavior:** All calls take approx same time (or perhaps first call is slow and all others are fast)

**Actual behavior:** first X are fast, all subsequent are very slow

### Versions

IronPython 2.7.8 2.7.8.0 on .NET 4.0.30319.42000

**Comment by tinyg** [comment]
I only vaguely understand what the weakref code is trying to do but, running the attached code, the WeakRefTracker for @ref gets hundreds of thousands of null callbacks registered against it which seems pointless.

If you replace line 784 in \ironpython2\Src\IronPython.Modules\_weakref.cs which currently reads:

```
wrt.ChainCallback(callback, self);
```

with:

```
if (callback != null) {
    wrt.ChainCallback(callback, self);
}
```

then only references with callbacks will actually be added to the tracker - this causes the sample to work fine for millions of runs.

I don't see any value in the null callback registrations however I might be missing something.

**Comment by slozier** [comment]
@tinyg Sounds like a reasonable fix. Perhaps move the `null` check into the `ChainCallback` method to make it a noop?

**Comment by slozier** [comment]
Hmm, will have to look into it some more. It looks like there's some code (in `__new__` which uses the fact that the callback is null to do something...

**Comment by slozier** [comment]
Here's a test case which needs to pass:
```Python
import weakref
class SomeWeakReferenceableObject(object): pass

o = SomeWeakReferenceableObject()
x = [weakref.ref(o) for i in range(10)]
assert weakref.getweakrefcount(o) == 1
```
It fails with the current bits (`getweakrefcount` gives 10), but also with the proposed fix (gives 0).

The following ugly code (the WeakRefTracker APIs are terrible) seems to work:
```C#
if (callback == null) {
    var found = false;
    for (int i = 0; i < wrt.HandlerCount; i++) {
        if (wrt.GetHandlerCallback(i) == null &&
            wrt.GetWeakRef(i) == self) {
            found = true;
            break;
        }
    }
    if (!found)
        wrt.ChainCallback(callback, self);
} else {
    wrt.ChainCallback(callback, self);
}
```

**Comment by tinyg** [comment]
I agree - that seems to work and fixes my test case also.

I do note that, if I leave my test case running, something is gradually leaking memory - maybe 1MB per minute

**Comment by tinyg** [comment]
Hmm - using dotMemory to profile it, i can see that it's unmanaged memory which is leaking so probably pretty hard to track down....
