### ISSUE TITLE
Move zlib.net from DLR back to ironpython

### ISSUE THREAD

**Issue by slozier** [IronLanguages/ironpython2#455]
I'm not really sure why it was moved in the first place, it's not used by any DLR code. Maybe so it's available to anything that uses the DLR?

In theory this change would just be a copy/paste.

**Comment by slide** [comment]
Can we do everything we need to with System.IO.Compression?

**Comment by slozier** [comment]
I don't think so, the zlib stuff that we would need isn't available.
