### ISSUE TITLE
Unable to build in Release mode in a UWP project

### ISSUE THREAD

**Issue by zhuxinghan** [IronLanguages/ironpython2#481]
I use IronPython in a UWP project, it works well in the Debug mode. But when I want to build a release app package, the build process failed and Visual Studio said "ilc.exe exited with error code 1200".

So is IronPython compatible with UWP? If not, why there are no problems in Debug mode?

The steps to reproduce the problem are simple: just create a blank UWP project and install IronPython and its dependencies from NuGet; Switch to Release mode and build the app, then it fails.

**Comment by slide** [comment]
How did you install IronPython from NuGet? I get errors that there are no compatible versions when trying to install it.

**Comment by zhuxinghan** [comment]
Sorry for missing an important point. Because IronPython targets on .Net Core 2.0, to create a UWP app that uses .Net Core 2.0, the min target OS version should be 1709(Fall Creators Update, 16299) or higher.

So when creating a UWP project and VS asking you to choose target versions, you should select 16299 or 17134(i.e. 1803) for the min version. The dialog may like this:
![version](https://user-images.githubusercontent.com/15711862/43590420-893da6c8-96a3-11e8-99dc-59dcbf92a565.jpg)

You can also change target versions for an existing project by opening Properties in the Solution Explorer. After changing the min version, IronPython should be able to be installed.

**Comment by slide** [comment]
I don't think this issue is specific to IronPython. I've read online in various places that building in Release mode can cause this issue in UWP applications. You probably need to raise an issue on the Visual Studio issues area.

**Comment by zhuxinghan** [comment]
Thank you anyway. Hope VS will fix the issue in the future and I will use other ways to use IronPython before that happens.
