### ISSUE TITLE
a = 'a' returns False

### ISSUE THREAD

**Issue by puru119** [IronLanguages/ironpython2#502]
Version: IronPython 2.7.8 (2.7.8.0) on .NET 4.0.30319.42000 (64-bit)

[Case 1]
>>> a = 'a'
>>> a is 'a'
False

[Case 2]
:: test.py
a = 'a'
while 1:
    a = 'a'
    print a is 'a'
- First, it prints 'False' and for a while it starts to print 'True'

**Comment by slozier** [comment]
Seems more like an implementation detail than a bug. Since strings are immutable Python doesn't guarantee that it won't reuse the same string object for equivalent strings (in fact CPython does this for short strings `'a' is 'a' == True`).

**Comment by puru119** [comment]
I did more test. The result tells me that the id('a') is not consistent. 
In my test, it's changing 109 to 108 while id(a) has consistent value 108.
On the contrary, on CPython the result always consistent.

I attach my test result.
[Code]
while 1:
    a = 'a'
    print "a is 'a' = {}, id(a)={}, id('a')={}".format(a is 'a', id(a), id('a'))

[Result - IronPython]
a is 'a' = False, id(a)=108, id('a')=109
a is 'a' = False, id(a)=108, id('a')=109
a is 'a' = False, id(a)=108, id('a')=109
a is 'a' = False, id(a)=108, id('a')=109
a is 'a' = False, id(a)=108, id('a')=109
a is 'a' = False, id(a)=108, id('a')=109
a is 'a' = False, id(a)=108, id('a')=109
a is 'a' = False, id(a)=108, id('a')=109
a is 'a' = False, id(a)=108, id('a')=109     <----
a is 'a' = True, id(a)=108, id('a')=108      <----
a is 'a' = True, id(a)=108, id('a')=108
a is 'a' = True, id(a)=108, id('a')=108
a is 'a' = True, id(a)=108, id('a')=108
a is 'a' = True, id(a)=108, id('a')=108
a is 'a' = True, id(a)=108, id('a')=108

[Result - CPython]
a is 'a' = True, id(a)=48197960, id('a')=48197960
a is 'a' = True, id(a)=48197960, id('a')=48197960
a is 'a' = True, id(a)=48197960, id('a')=48197960
a is 'a' = True, id(a)=48197960, id('a')=48197960
a is 'a' = True, id(a)=48197960, id('a')=48197960
a is 'a' = True, id(a)=48197960, id('a')=48197960
a is 'a' = True, id(a)=48197960, id('a')=48197960
a is 'a' = True, id(a)=48197960, id('a')=48197960
a is 'a' = True, id(a)=48197960, id('a')=48197960
a is 'a' = True, id(a)=48197960, id('a')=48197960
a is 'a' = True, id(a)=48197960, id('a')=48197960
a is 'a' = True, id(a)=48197960, id('a')=48197960
a is 'a' = True, id(a)=48197960, id('a')=48197960
a is 'a' = True, id(a)=48197960, id('a')=48197960
a is 'a' = True, id(a)=48197960, id('a')=48197960
a is 'a' = True, id(a)=48197960, id('a')=48197960
a is 'a' = True, id(a)=48197960, id('a')=48197960
a is 'a' = True, id(a)=48197960, id('a')=48197960

**Comment by puru119** [comment]
Attach another test result. I compared 'a' and 'a', which is 'a' is 'a', and the result can be False.

[Code]
while 1:
    print "'a' is 'a' = {}, id('a')={}, id('a')={}".format('a' is 'a', id('a'), id('a'))


[Result]
'a' is 'a' = False, id('a')=108, id('a')=109
'a' is 'a' = False, id('a')=108, id('a')=109
'a' is 'a' = False, id('a')=108, id('a')=109
'a' is 'a' = False, id('a')=108, id('a')=109
'a' is 'a' = False, id('a')=108, id('a')=109
'a' is 'a' = False, id('a')=108, id('a')=109
'a' is 'a' = False, id('a')=108, id('a')=109
'a' is 'a' = False, id('a')=108, id('a')=109
'a' is 'a' = False, id('a')=108, id('a')=109
'a' is 'a' = False, id('a')=108, id('a')=109
'a' is 'a' = True, id('a')=110, id('a')=110
'a' is 'a' = True, id('a')=110, id('a')=110
'a' is 'a' = True, id('a')=110, id('a')=110
'a' is 'a' = True, id('a')=110, id('a')=110
'a' is 'a' = True, id('a')=110, id('a')=110
'a' is 'a' = True, id('a')=110, id('a')=110
'a' is 'a' = True, id('a')=110, id('a')=110
'a' is 'a' = True, id('a')=110, id('a')=110
'a' is 'a' = True, id('a')=110, id('a')=110
'a' is 'a' = True, id('a')=110, id('a')=110
'a' is 'a' = True, id('a')=110, id('a')=110
'a' is 'a' = True, id('a')=110, id('a')=110

**Comment by pekkaklarck** [comment]
This is definitely an implementation detail. As already mentioned, also CPython often reuses the same string object but that doesn't occur always and results can be strange:

```
>>> 'foo' is 'foo'
True
>>> 'foo' is 'f' + 'o' + 'o'
True
>>> 'foo' is 'f' + 'o' * 2
False
```

You shouldn't use `is` with strings in general. Using `==` above would yield True every time.
