### ISSUE TITLE
Question about .NET 3.5 release

### ISSUE THREAD

**Issue by dretax** [IronLanguages/ironpython2#509]
Is there a pre compiled release for .NET 3.5?
Im not able to find it, but the site states the project is compatible with it.

**Comment by simplicbe** [comment]
As far as I know the project is migrated to .net 4, because of the DLR.

**Comment by dretax** [comment]
Ahh. Do you know by any chance which one was the last version supporting 3.5?
I have a really old one from 2014, and this issue caused me a lot of pain before.
https://bugzilla.xamarin.com/show_bug.cgi?id=8117

**Comment by slozier** [comment]
2.7.7 is the last release that is compiled for net35. You can find the release at https://github.com/IronLanguages/main/releases
