### ISSUE TITLE
Error Installing Package Pandapower in IronPython 2.7.9 RC1

### ISSUE THREAD

**Issue by GirishVC86** [IronLanguages/ironpython2#516]
TypeError: a new-style class can't have only classic bases

Steps to Reproduce

C:\Windows\system32>ipy -X:Frames -m pip install --upgrade pip
Collecting pip
  Using cached https://files.pythonhosted.org/packages/5f/25/e52d3f31441505a5f3af41213346e5b6c221c9e086a166f3703d2ddaf940/pip-18.0-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 8.1.1
    Uninstalling pip-8.1.1:
      Successfully uninstalled pip-8.1.1
Successfully installed pip-18.0

C:\Windows\system32>ipy -X:Frames -m pip install --upgrade setuptools
Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/66/e8/570bb5ca88a8bcd2a1db9c6246bb66615750663ffaaeada95b04ffe74e12/setuptools-40.2.0-py2.py3-none-any.whl (568kB)
    100% |################################| 573kB 726kB/s
Installing collected packages: setuptools
  Found existing installation: setuptools 20.10.1
    Uninstalling setuptools-20.10.1:
      Successfully uninstalled setuptools-20.10.1
Successfully installed setuptools-40.2.0

C:\Windows\system32>ipy -X:Frames -m pip install --upgrade pandapower
Collecting pandapower
  Using cached https://files.pythonhosted.org/packages/5c/7c/24cc90afc729b3cbce4fdd0b88ca395f17aebfea6184c90c424e6a862816/pandapower-1.5.1.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Program Files\IronPython 2.7\Lib\site-packages\setuptools\__init__.py", line 148, in <module>
    TypeError: a new-style class can't have only classic bases

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\41008950\appdata\local\temp\pip-install-lrqri4\pandapower\

Versions
IronPython 2.7.9rc1 2.7.9.0 on .NET 4.0.30319.42000

**Comment by slozier** [comment]
When I tried it over here it was failing when trying to install numpy which unfortunately isn't supported.

**Comment by slide** [comment]
Also, you no longer need to use -X:Frames when using pip. Frames are turned on by default with 2.7.9
