### ISSUE TITLE
cElementTree missing

### ISSUE THREAD

**Issue by pekkaklarck** [IronLanguages/ironpython2#518]
IronPython now has working ElementTree (#370) but cElementTree is still missing. It means Python code using that more efficient variant won't work with IronPython. Luckily a common idiom is using

```python
try:
    from xml.etree import cElementTree as ET
except ImportError:
    from xml.etree import ElementTree as ET
```

but that causes one unnecessary ImportError.

I don't think IronPython actually needs a separate cElementTree implementation, but having a wrapper for it would be useful. That's exactly what Python 3 does:
https://github.com/python/cpython/blob/3.7/Lib/xml/etree/cElementTree.py

**Comment by slide** [comment]
Fixed in #521
