### ISSUE TITLE
Fast copying in SetStorage.Clone introduces empty buckets

### ISSUE THREAD

**Issue by johanndprover** [IronLanguages/ironpython2#519]
https://github.com/IronLanguages/ironpython2/blob/df6b20cdaeb03cdbc9d24c5f88a12fc07a88f640/Src/IronPython/Runtime/SetStorage.cs#L267

The collision handling mechanism relies on no empty bucket (bucket.item == null) lying between the start index (hashCode % buckets.Length) and the actual index where an item is inserted. To maintain this invariant when an element is removed, its bucket is assigned a special Removed object rather than null.

When fast-copying buckets in SetStorage.Clone, buckets marked as Removed must remain marked, or later calls to SetStorage.ContainAlwaysHash can incorrectly return false for items that are present after empty buckets.

A fix for #152 ago broke that invariant.

**Comment by slozier** [comment]
Repro code for the issue:
```Python
x = set(range(8))
x.add(16)
x.remove(0)
assert 16 in x
assert 16 in set(x)
```
