### ISSUE TITLE
sqlite3 execute faild and the exception is expected buffer object

### ISSUE THREAD

**Issue by liyuaq1986** [IronLanguages/ironpython2#522]
using the follow db and just execute sql  the the program crashed。
sql = 'select msgseq,extstr,frienduin,msgdata,senderuin,time,msgtype ,_id from mr_friend_373B750958FA49CDF32A08407A21CEDC_New order by time'
 

[848565664.zip](https://github.com/IronLanguages/ironpython2/files/2378351/848565664.zip)

**Comment by liyuaq1986** [comment]
so what's your meaning. i don't understand. can you say it clearly.

**Comment by slozier** [comment]
It's an example of the issue you are experiencing without having to use your sample database.

**Comment by liyuaq1986** [comment]
I just say  the  problem of  sqlite3 on iron python while using cpython sqlite3  has no problem. so ...do you understand the key problem.?

**Comment by slozier** [comment]
Yes, the key problem is understood. Thank you for the report.
