### ISSUE TITLE
IronPython.StdLib 2.7.8.1 Nuget Package not creating a content directory

### ISSUE THREAD

**Issue by TimDN** [IronLanguages/ironpython2#525]
### Description

Installing IronPython.StdLib 2.7.8.1 using Nuget will not pull in the Lib to the project. The Nuget package for 2.7.8.1 only creates a contentFiles directory in the package. From what i understand only .Net Core use contentFiles. For a Nuget package to support both .Net Framework and .Net Core it needs to create a contentFiles and a content directory.

### Steps to Reproduce

1. Create a new project targeting .NetFrameWork 4.6.2
2. Install the Nuget Package IronPython.StdLib 2.7.8.1
3. Compile

**Expected behavior:** 
A Lib folder should be in the project and should be included in the output when compiling the project.

**Actual behavior:**
There is no Lib folder and nothing is included when compiling the project.

### Versions
 IronPython.StdLib 2.7.8.1
 .Net Framework 4.6.2

**Comment by TimDN** [comment]
Note that 2.7.9 candidate1 is not working either

**Comment by slide** [comment]
I checked into the docs and it looks like projects that use packages.config need to use content and ones that use PackageReference need contentFiles. We should be able to fix it up in the next RC.

**Comment by ferronsw** [comment]
The Lib folder is not copied to the bin debug or release folder.

I'm using IronPython 2.7.11 and .Net 4.8

**Comment by slozier** [comment]
@ferronsw Works fine for me. Are you using `PackageReference`?
```
<PackageReference Include="IronPython.StdLib" Version="2.7.11" />
```

**Comment by ferronsw** [comment]
@slozier upgrading from packages.config to packagereference helped, thanks!
