### ISSUE TITLE
Installer does not remember selection

### ISSUE THREAD

**Issue by slozier** [IronLanguages/ironpython2#535]
If you install IronPython with pip and go to `Apps & Features -> IronPython 2.7.9 -> Modify -> Change` pip will be marked as not installed. A consequence of this is if you do a `Repair` then pip will be removed from the system.

**Comment by slozier** [comment]
Also using Change to try to readd pip doesn't seem to work.

**Comment by slide** [comment]
I decided to remove the modify and repair options from the installer.
