### ISSUE TITLE
position paramters of function unstable on ARM platform

### ISSUE THREAD

**Issue by equiclouds** [IronLanguages/ironpython2#549]
I installed ironpython2.7.9 on rasperberry, and code bellow:
```python
class test:
    def extend(self, a, *b):
        return a, b
def main():
    c1 = test().extend({},{})
    for i in range(0,100):
        c2 = test().extend({},{})
        if c1!=c2:
            return i,c1,c2
main()
```

Randomly, after some times, the extend function b paramters will be valued with test() object...

```
root@raspberrypi:/tmp/tmp# ipy test.ipy 
(39, ({}, ({},)), ({}, <__main__.test instance at 0x000000000000006C>))
root@raspberrypi:/tmp/tmp# ipy test.ipy 
(82, ({}, ({},)), ({}, <__main__.test instance at 0x000000000000006C>))
root@raspberrypi:/tmp/tmp# vim test.ipy
```

**Comment by slide** [comment]
If the same code functions correctly on a non-ARM device, then this is probably some issue with Mono.

**Comment by slide** [comment]
Does it work correctly on an x86 machine under mono?

**Comment by equiclouds** [comment]
Yes, it return None on X86 machine under mono 5.16 with IronPython 2.7.9.

```python
class test:
    def extend(self, a, *b):
        return a, b
def main():
    c1 = test().extend({},{})
    for i in range(0,100):
        c2 = test().extend({},{})
        if c1!=c2:
            print(i,c1,c2)
            return
main()
```

It seams that the after random times run, the function of instance will pass the instance itself as value of *b paremeter:

root@raspberrypi:/tmp/tmp# ipy test.ipy 
(39, ({}, ({},)), ({}, <__main__.test instance at 0x000000000000006C>))
root@raspberrypi:/tmp/tmp# ipy test.ipy 
(82, ({}, ({},)), ({}, <__main__.test instance at 0x000000000000006C>))

the result shos that after run 39 or 82 times, the value of b paremter is an instance of test class

**Comment by equiclouds** [comment]
But everything is OK with non-instance funtions:

```python
def extend(a, *b):
    return a, b
def main():
    c1 = extend({},{})
    for i in range(0,100):
        c2 = extend({},{})
        if c1!=c2:
            return i,c1,c2
main()
```

The code above return None on both ARM and X86 devices.

**Comment by slide** [comment]
If it works on x86 and not on ARM, then you would probably want to file a bug against mono. We rely on the behavior of the runtime to be the same across architectures, if it isn't, then there is a bug in mono.

**Comment by slozier** [comment]
I tried the following (Raspbian under QEMU) and it ended up killing Mono:
```Python
class test:
    def extend(self, a, *b):
        return b

call = test.extend.__func__.__call__

def main():
    for i in range(100):
        call(test(), None)

main()
main()
main()
# ...run main() a few times
```

**Comment by slide** [comment]
Is there a stacktrace?

**Comment by slozier** [comment]
[test.txt](https://github.com/IronLanguages/ironpython2/files/2642004/test.txt)

**Comment by slozier** [comment]
Tried on Raspbian with latest bits and Mono 6.8.0.105 as well as .NET Core 3.1 and it doesn't appear to be an issue anymore.
