### ISSUE TITLE
about _gdal.pyd

### ISSUE THREAD

**Issue by 748448660** [IronLanguages/ironpython2#550]
Hi
  I used gdal by ironpython . Gdal.py in 'osgeo' folder that calls  _gdal.pyd file.  I use ipy32.exe to input 'import gdal' .It is throw a  exception that no module named _gdal but it is not problem in python.exe.My sys.path includes those environment. Does the problem lie with **.pyd** File?
I look forward to your reply.

**Comment by slide** [comment]
A .pyd file is a C based module. IronPython does not support C based modules
