### ISSUE TITLE
`time.altzone` has wrong value

### ISSUE THREAD

**Issue by pekkaklarck** [IronLanguages/ironpython2#553]
Some of our time related tests fail on IronPython and after some investigation noticed that IronPython has wrong [time.altzone](https://docs.python.org/3/library/time.html#time.altzone) value. I got these results with Python 2.7 and IronPython 2.7.9 here in Finland:

```
E:\>python -c "import time; print time.timezone, time.altzone, time.tzname"
-7200 -10800 ('FLE Standard Time', 'FLE Daylight Time')

E:\>ipy -c "import time; print time.timezone, time.altzone, time.tzname"
-7200 -7200 ('FLE Standard Time', 'FLE Daylight Time')
```

As you can see, timezone names are same (apparently Microsoft prefers that strange FLE over EET), the normal timezone values are right, but with IronPython the DST timezone is incorrect.

I don't remember these tests failing earlier. Could it be that with IronPython `time.altzone` value depends on is DST actually active or not? We has DST change somewhat recently and that would explain.

**Comment by slide** [comment]
I believe this is fixed via https://github.com/IronLanguages/ironpython2/pull/555
