### ISSUE TITLE
Questions about the ironpython library

### ISSUE THREAD

**Issue by cpalominoch** [IronLanguages/ironpython2#570]
Dear,
I have a query about the python libraries:
- In the new version of IronPython 2.7 the library includes numpy, scipy, math?
-IronPython will be compatible with the new versions of Python 2.7, 3.3, 3.4, 3.5, 3.6 and 3.7?

**Comment by slide** [comment]
numpy and scipy are not currently supported, they use notice C libraries. IronPython 2.7 is compatible with Python 2.7. Please use the mailing list for questions
