### ISSUE TITLE
Embedded IPY engine fails to create new engine with diffrent AppDomain when hooking AppDomain.AssemblyResolve

### ISSUE THREAD

**Issue by byt3bl33d3r** [IronLanguages/ironpython2#592]
### Description

Hooking the `AppDomain.CurrentDomain.AssemblyResolve` function to reflectively load the IronPython and Microsoft.Scripting assemblies (without an image backing on disk) and then trying to create a new IPY engine in a "sandboxed" AppDomain using `Python.CreateEngine(SandboxedAppdomain)` results in a `SerializationException` error. It does seem to work fine if the DLLs are in the same folder as the executing assembly. However the use case here is deploying a C# application on machines without IronPython installed and I believe this should work? I might be missing something obvious.

Also I got this to work perfectly if I just call `Python.CreateEngine()` without specifying a new AppDomain, this is what makes me inclined to believe this is a bug.

I did some googling and found this ancient thread in which someone seems to have encountered the same issue:
- https://mail.python.org/pipermail/ironpython-users/2009-December/011764.html
- https://mail.python.org/pipermail/ironpython-users/2009-November/011580.html

### Steps to Reproduce

```csharp
class Program
{
    private static Assembly MyResolveEventHandler(object sender, ResolveEventArgs args)
    {
         /* Reflectively load the DLLs here via Assembly.Load() */
         return Assembly.Load();
    }

   public static void Main(string[] args)
    {
         AppDomain.CurrentDomain.AssemblyResolve += new ResolveEventHandler(MyResolveEventHandler)
         AppDomain appDomain = AppDomain.CreateDomain("IPY");
         var engine = Python.CreateEngine(appDomain);
         engine.Execute("print 'wat'");
    }
}
```
Run the above code on a machine without IronPython installed will result in a serialization error

**Expected behavior:** [What you expected to happen]
Unless I'm missing a key limitation somewhere, I don't see why this shouldn't be possible?

**Actual behavior:** [What actually happened]
A `SerializationException` occurs when creating a new Python Engine in a diffrent AppDomain:

```csharp
Unhandled Exception: System.Runtime.Serialization.SerializationException: Type is not resolved for member 'Microsoft.Scripting.Hosting.ScriptRuntimeSetup,Microsoft.Scripting, Version=1.2.2.0, Culture=neutral, PublicKeyToken=7f709c5b713576e1'.
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at Microsoft.Scripting.Hosting.ScriptRuntime.CreateRemote(AppDomain domain, ScriptRuntimeSetup setup)
   at ST.CreateEngine()
   at ST.RunIPYEngine()
   at ST.Main(String[] args)
```

### Versions
`IronPython 2.7.9 (2.7.9.0) on .NET 4.0.30319.42000 (64-bit)` on Windows 10

**Comment by slozier** [comment]
Did you try hooking up your resolver to your `appDomain` as well?

**Comment by byt3bl33d3r** [comment]
as in the following?
```csharp
AppDomain appDomain = AppDomain.CreateDomain("IPY");
appDomain.AssemblyResolve += new ResolveEventHandler(MyResolveEventHandler);
```
If so i have tried that, no dice

**Comment by slozier** [comment]
Hmm, doing that worked for me. And your resolver is properly resolving the assemblies when called in the AppDomain?

**Comment by byt3bl33d3r** [comment]
You're right it is working, it was a combination of me not understanding how appdomains works and a logic bug in my resolver code. Just got it working.

Thanks!
