### ISSUE TITLE
Error while importing .NET assembly

### ISSUE THREAD

**Issue by maxmont** [IronLanguages/ironpython2#597]
Hi all, I'm trying to use mathematic commercial .NET library in IronPython environnement.
With ipy console, everything is working.
But when I try to execute the same code with my app, I get an error : 
"ImportError: No module named Mathematics"

The code is  : 

import clr
clr.AddReferenceToFileAndPath(r"Extreme.Numerics.dll")
from Extreme.Mathematics.Curves import *

I don't see the difference between ipy execution context and my app execution context.

Do you have an idea about the root cause of this issue?

Thanks in advance for your help

**Comment by slozier** [comment]
Works fine for me. You'll have to post a sample program reproducing the issue...

**Comment by maxmont** [comment]
@slozier I've found the issue but I don't know why it's not working....
In fact before starting execution, I add a directory in searchdirectories collection (like that m_Engine.SetSearchPaths(.....)). I add the directory which contains the python script I execute.
If I don't add this directory, it's working.
I don't see why????

**Comment by maxmont** [comment]
If I don't add this directory in searchdirectories list, I can't import module which is in the same directory than the executed script.

**Comment by slozier** [comment]
When you do `SetSearchPaths` it replaces whatever search paths are already there. That might why it doesn't work when you set it. Maybe try:
```C#
var paths = engine.GetSearchPaths();
paths.Add(@"...");
engine.SetSearchPaths(paths);
```

Also, `clr.AddReferenceToFileAndPath` will add the directory to the search path so you don't need to manually add it (using ``engine.SetSearchPaths`), however, in your example you are not specifying the directory so it will add the current working directory. You can see the search paths using `print(sys.path)`.

**Comment by maxmont** [comment]
@slozier In fact I do what you say : 
`var paths = engine.GetSearchPaths();
paths.Add(@"...");
engine.SetSearchPaths(paths);`

**Comment by maxmont** [comment]
@slozier I found my mistake. I named my sample script Extreme.py. It bring a confusion with extreme library. Everything is working now. Thanks
