### ISSUE TITLE
.Net Standard support 

### ISSUE THREAD

**Issue by YairHalberstadt** [IronLanguages/ironpython2#598]
Are there any plans to support .Net Standard in the future?
.Net Core and .Net Framework are already supported, so I'm guessing this shouldn't be impossible.

Thanks for all your great work on IronPython - it's really appreciated, and we use it heavily for our plugin system. Unfortunately that's currently holding us back from porting our application to .Net Standard...

**Comment by slozier** [comment]
Same comment as https://github.com/IronLanguages/dlr/issues/175

**Comment by slozier** [comment]
Resolved by https://github.com/IronLanguages/ironpython2/pull/599
