### ISSUE TITLE
Cannot import name Directory by IronPython 2.7.9 in .NET Core

### ISSUE THREAD

**Issue by equiclouds** [IronLanguages/ironpython2#611]
Can not import Directory
```python
from System.IO import Directory
```

Can import  Path

```python
from System.IO import Path
```

**Comment by slozier** [comment]
`Directory` is in a different assembly in .NET Core. You will need to add a reference before you can import:
```Python
import clr
clr.AddReference("System.IO.FileSystem")

from System.IO import Directory
```

**Comment by equiclouds** [comment]
Thanks a lot, I have made System.IO.FileSystem defaut loaded. 
How many other common used classes like Directory are in different assemblies?

**Comment by slozier** [comment]
It looks like only type from `System.Private.CoreLib` are loaded automatically. I thought adding a reference to `mscorlib` would work to resolve common types would work but apparently it's not, I will have to investigate.
