### ISSUE TITLE
os.system error on NET CORE

### ISSUE THREAD

**Issue by equiclouds** [IronLanguages/ironpython2#612]
The code:

```python
import os
os.system("dir")
```

Error got:

```
System.TypeLoadException: Could not load type 'System.Runtime.CompilerServices.Closure' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
```

Does the StdLib doesn't adapt to net core yes?

**Comment by slozier** [comment]
Are you using some compiled (with the .NET Framework) Python code? This will not work with .NET Core. Unfortunately there is no way to compile Python code into a DLL with .NET Core.

**Comment by equiclouds** [comment]
I try to compile Python code into a Dll with .NET Core, got error:

```
System.NotSupportedException: Specified method is not supported.
   at Microsoft.Scripting.SavableScriptCode.CompileForSave(TypeGen typeGen)
   at Microsoft.Scripting.SavableScriptCode.SaveToAssembly(String assemblyName, IDictionary`2 assemblyAttributes, SavableScriptCode[] codes)
```

Can we implement the CompileForSave method by ourself?

**Comment by slozier** [comment]
Right now it uses `AssemblyBuilder.Save` which isn't available on .NET Core, so probably not easily...

**Comment by slozier** [comment]
Duplicate of https://github.com/IronLanguages/ironpython2/issues/351
