### ISSUE TITLE
Autocomplete works, but Intellisense does not

### ISSUE THREAD

**Issue by dbmercer** [IronLanguages/ironpython2#615]
_Originally reported on [StackOverflow](https://stackoverflow.com/questions/55714098/how-to-resolve-unresolved-import-xxx-in-a-visual-studio-ironpython-environme). Someone from MSFT reproduced the issue and suggested I report it here._

I am developing IronPython scripts in Visual Studio 2019.

- The Python scripts work (i.e., they run without error).
- Visual Studio's autocomplete correctly offers options (`clr`, `sys`, `System`) when I type `import`_&lt;space>_.

But when I type (or select) a choice on the list, it gets flagged (underlined in a squiggly green) with the error `Unresolved import 'XXX'` (where "XXX" is one of the choices on the autocomplete list). Within the editor, it is clear that the modules (namespaces) were not imported (i.e., no autocomplete on the imported modules).

Autocomplete works, but Intellisense (or the analyzer) does not.

I have tried both 64- and 32-bit IronPython 2.7 environments. I have also tried typing the import statements into the interactive window without error. And, as I said above, the scripts work. I can run them and they work.

The code to reproduce is quite simple:

```python
import System
import clr
import sys
```

All 3 of those examples work with autocomplete. All 3 of those lines get flagged as unresolved and do not import within the editor.

**Comment by slozier** [comment]
I believe this is a PTVS issue. See https://github.com/Microsoft/PTVS/issues/5027

**Comment by RaymonGulati1** [comment]
Also reported at: https://developercommunity.visualstudio.com/content/problem/543859/ironpython-autocomplete-works-but-intellisense-doe.html

**Comment by Krytical13** [comment]
I'm seeing the same behavior with visual studio 2019 and a standard python 3.7 project.
(not IronPython)
example:
from bs4 import BeautifulSoup4

PyLint: unresolved import 'bs4' 
MyPy:  No library stub file for module 'bs4'

In my case though, Code still executes. Autocomplete works. IntelliSense works.

**Comment by slozier** [comment]
Closing this as it's a PTVS issue. Unfortunately it seems like they have no plans to do additional work specifically for IronPython since usage it too low (see https://github.com/microsoft/PTVS/issues/5027#issuecomment-556169802).

@Krytical13 I suggest you try filing your issue on https://github.com/microsoft/PTVS
