### ISSUE TITLE
problem with Ironpython to work with opencv

### ISSUE THREAD

**Issue by AminDarestani2019** [IronLanguages/ironpython2#616]
Dears,
i need to use python in Csharp so i select IronPython2.7 from nuggets but there are some problems in using OpenCV or some other python modules .
for example:
Additional information: unexpected token 'from'
or 
no named module 'CV2'
would u please help me to do it?
thanks

**Comment by slozier** [comment]
Unfortunately the OpenCV package (`opencv-python`) appears to be a C module which requires CPython. It will not work with IronPython.
