### ISSUE TITLE
ImportExtensions fails on .NET Core

### ISSUE THREAD

**Issue by napalu** [IronLanguages/ironpython2#617]
### Description
Couldn't find mention of this problem in the issues.
Running IronPython 2.7.9 on Linux with .NET Core 2.2. It seems clr extensions don't get properly loaded as illustrated by the example below.

### Steps to Reproduce

The code below runs fine on Net framework 4.5+ but fails on .NET Core:

```c#

using System;
using System.Collections.Generic;
using System.Linq;
using IronPython.Hosting;

namespace IronPythonTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var data = new List<string>
            {
                "one",
                "two"
            };
            const string source = @"

import clr
clr.AddReference('System')
clr.AddReference('System.Core')
from System import Linq
clr.ImportExtensions(Linq)
from System.Collections.Generic import List

def test(d):
    return d.Last()

test(data)
";
            var engine = Python.CreateEngine();
            var scope = engine.CreateScope();
            scope.SetVariable("data", data);
            try
            {
                var returnValue = engine.Execute<string>(source, scope);
                Console.WriteLine("Last() == {0}: {1}", returnValue, returnValue == data.Last());
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
            }
            
            
        }
    }
}
```

**Expected behavior:** [What you expected to happen]
Linq Last() method should be loaded from clr

**Actual behavior:** 
Fails with message: `'List[str]' object has no attribute 'Last'`

### Versions
Tested with nuget IronPython 2.7.9 and .NET Core 2.2 on both Linux and Windows-

**Comment by slozier** [comment]
Not exactly sure why it's not picking up the extension, but you can work around it by adding `clr.AddReference('System.Linq')`.

**Comment by napalu** [comment]
Hi slozier

Thanks - the workaround works fine - bit of a pain catching the exception and injecting the appropriate stanza in existing scripts but it's a lot better than them not working :)
