### ISSUE TITLE
Inaccessible method without [PythonHidden] attribute

### ISSUE THREAD

**Issue by sensokame** [IronLanguages/ironpython2#625]
Hello, while using IronPython I came across the distinction between python accessible methods and non accessible methods using the PythonHiddenAttribute, when using the List I came across this issue.
I believe that this public CopyTo method should have a [PythonHidden] attribute just like the other one
https://github.com/IronLanguages/ironpython2/blob/d371715f0bf7fee2b438e392635b9d5a02519425/Src/IronPython/Runtime/List.cs#L1359

Edit: you guys are doing some great work with this library, keep it up

**Comment by slozier** [comment]
Thanks, this is probably a good addition.

I'm just wondering where you ran into this method? If it was from the Python side of things then there may be other issues? Generally if one overload is tagged with `PythonHidden` then the rest are also hidden.

**Comment by sensokame** [comment]
While using reflection in c# code to retrieve list methods that are accessible, I tried to exclude the ones marked with the python hidden custom attribute and this one passed through 😛
