### ISSUE TITLE
First script execution, CPU usage rise to 75%

### ISSUE THREAD

**Issue by NaolShow** [IronLanguages/ironpython2#631]
### Description

Hello everyone!

ONLY for the first execution of a python script, (only the first!) my cpu usage rise to 75%.
And I get a lot of errors in the console.
And I don't know why.
The code in the py file is working.

I don't know if it's important, but I'm starting the script in another thread (to prevent app from freezing):

           private static void Execute() {
            try {
                Task.Run(() => ExecuteCommandFunction());

            } catch (Exception e) {

                Utils.Log(e.Message);

            }
          }
           private static void ExecuteCommandFunction() {

            // Execute
            var _Source = Engine.CreateScriptSourceFromFile("python_script.py"));
            _Source.Execute(Scope);

        }

### Steps to Reproduce

Just start a Python script

**Actual behavior:** Lot of errors:

`Exception thrown: 'IronPython.Runtime.Exceptions.ImportException' in IronPython.Modules.dll
Exception thrown: 'System.Reflection.TargetInvocationException' in mscorlib.dll
Exception thrown: 'IronPython.Runtime.Exceptions.ImportException' in Microsoft.Dynamic.dll
Exception thrown: 'IronPython.Runtime.Exceptions.ImportException' in Microsoft.Dynamic.dll
Exception thrown: 'IronPython.Runtime.Exceptions.ImportException' in IronPython.Modules.dll
Exception thrown: 'System.Reflection.TargetInvocationException' in mscorlib.dll
Exception thrown: 'IronPython.Runtime.Exceptions.ImportException' in Microsoft.Dynamic.dll
Exception thrown: 'IronPython.Runtime.Exceptions.ImportException' in Microsoft.Dynamic.dll
'Wolfy.exe' (CLR v4.0.30319: Wolfy.exe): Loaded 'Anonymously Hosted DynamicMethods Assembly'. 
'Wolfy.exe' (CLR v4.0.30319: Wolfy.exe): Loaded 'Snippets.scripting'. 
Exception thrown: 'IronPython.Runtime.Exceptions.ImportException' in IronPython.dll
Exception thrown: 'IronPython.Runtime.Exceptions.ImportException' in IronPython.dll
'Wolfy.exe' (CLR v4.0.30319: Wolfy.exe): Loaded 'Snippets'. 
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in mscorlib.dll
Exception thrown: 'System.TimeoutException' in WindowsBase.dll`

### Versions

I'm using the last version of IronPython.

Thanks for your help !

**Comment by slozier** [comment]
I'm unable to reproduce the issue over here. It's likely related to what's in your python file. If you just use a file with `print('Hello World!')` do you still get a big CPU spike and a bunch of errors?

**Comment by NaolShow** [comment]
Hello!
Thanks for your answer.

So I tried with a basic script: print("Hello world!")
And the CPU rise to 25% at the first start and only 3% other times,
but with only a print I do not get any errors

So I don't understand
(my previous code was:)
import subprocess
subprocess.Call("notepad.exe")

I forgot one thing, I have that code to initialize IronPython:

       private static void InitCommands() {

            // Engine
            Engine = Python.CreateEngine();

            // Modules
            var _Paths = Engine.GetSearchPaths();
            _Paths.Add(Reference.ModulesPath); // The module folder
            _Paths.Add(Reference.IronModules); // The IronPython.StdLib.2.7.9.zip
            Engine.SetSearchPaths(_Paths);

        }

**Comment by slozier** [comment]
The startup spike in CPU usage is probably normal since it's doing a bunch of initial work reading/parsing/compiling `subprocess` and all its dependencies. You don't see it the second time around since that work is already done and it can just run the code.

As for the import errors I'm not sure since I don't see any over here. This is my test program:
```C#
using IronPython.Hosting;
using Microsoft.Scripting.Hosting;
using System;
using System.Threading.Tasks;

namespace ConsoleApp22
{
    class Program
    {
        private static ScriptEngine Engine;
        private static ScriptScope Scope;

        static void Main(string[] args)
        {
            InitCommands();
            Console.ReadKey();
            while (true)
            {
                Execute();
                Console.ReadKey();
            }
        }

        private static void InitCommands()
        {
            // Engine
            Engine = Python.CreateEngine();
            Scope = Engine.CreateScope();

            // Modules
            var _Paths = Engine.GetSearchPaths();
            _Paths.Add("IronPython.StdLib.2.7.9.zip");
            Engine.SetSearchPaths(_Paths);
        }

        private static void Execute()
        {
            try
            {
                Task.Run(() => ExecuteCommandFunction());
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
            }
        }

        private static void ExecuteCommandFunction()
        {
            // Execute
            var _Source = Engine.CreateScriptSourceFromFile("python_script.py");
            _Source.Execute(Scope);
        }
    }
}
```

**Comment by NaolShow** [comment]
Ok I was thinking the CPU usage rise was due to the import errors.
But yes it's maybe because of the initialization!

Thank you for your help. If someone else has the solution to prevent import errors i'm here!
I'll still use my code , it's not really important for thoses errors!

Thanks :)
