### ISSUE TITLE
ironpython3

### ISSUE THREAD

**Issue by pro100coder18** [IronLanguages/ironpython2#638]
When will ironpython 3 be released?

**Comment by dancergraham** [comment]
Hello, According to the gitter channel the answer is 'when its ready' :(

https://gitter.im/IronLanguages/ironpython?at=5cee842c6f530d3b6101141c

**Comment by slozier** [comment]
Yes, unfortunately the answer is "when it's ready". We are working on it in our limited spare time which means that it's hard to establish a timeline. If you would like to help the project move forward, we're more than happy to accept contributions at https://github.com/IronLanguages/ironpython3.
