### ISSUE TITLE
On call of .py file function give Attempted “__set__” operation on ASN.1 schema object

### ISSUE THREAD

**Issue by sandeepDaya** [IronLanguages/ironpython2#641]
Hi,
when we are calling .py file function throught Ironpython like c# code. It was working fine but in case of dynamically import module in pythob file like importlib.import_module("test_manager.py") then a system gives  No module found "pyasn1.type.univ".

After installing "pyasn1.type.univ" system gives "Attempted “__set__” operation on ASN.1 schema object".

This error is a bottleneck of us. Please share some thing on it if you have idea/info about that.

Thanks,
Sandeep
sandeepdaya.kumar@gmail.com

**Comment by slozier** [comment]
I haven't been able to reproduce this over here. Do you have an simple example I can run to replicate the issue?
