### ISSUE TITLE
Unable to load IronPython assembly while running a .NETCore2.1 Console App on VS2019

### ISSUE THREAD

**Issue by Wizard2436829** [IronLanguages/ironpython2#642]
So I am trying to run a python script from my .NET Core App.

When the method that involves functions and classes, that are included in the IronPython Library, is invoked, it gives me the following error message :

Could not load file or assembly 'IronPython, Version=2.7.9.0, Culture=neutral, PublicKeyToken=7f709c5b713576e1'. An operation is not legal in the current state. (Exception from HRESULT: 0x80131509)

I had installed the IRON Python library for .NET using the Nuget Package Manager.
Also, the present version of python installed in my system is 3.7.3

Can you please provide a solution.

Thanks in advance

**Comment by slozier** [comment]
Could you provide an example to reproduce the issue?
