### ISSUE TITLE
IronPython install modules error (there is a simplier way ?)

### ISSUE THREAD

**Issue by NaolShow** [IronLanguages/ironpython2#646]
### Description

Hello everyone, thank you in advance for your help. I'm developing an application in C# on visual studio that aims to launch .py files using voice commands, so I use the ironpython library. The problem is that I would like to import modules to have more possibilities such as pressing keys.
But the problem is that I can't find an easy way to install modules for users. And even then, I can't install a module myself.... I tried importing it directly into the searchpath, but there was a lot of libraries missing so I gave up. And then I tried to install the ironpython.exe to go through ipy.exe, but there are only problems. I receive the following error message with each installation attempt:
You are using pip version 8.1.1, however version 19.1.1.1 is available.
You should consider upgrading via the'python -m pip install --upgrade pip' command.

While I have the latest version of IronPython (I even ordered: ipy -X:Frames -m ensurepip).

I've been straightening my hair for a few weeks now and I'm afraid I can't find a simple way to install modules

So would you have either a fix for ipy or a simpler way to install modules so that my users don't get lost? Thank you very much and have a good day!

### Steps to Reproduce

1.Install IronPython
2.Go to IronPython installation folder
3.Type in cmd: cd IRONPYTHONPATH
4.Type: ipy -X:Frames -m pip install pynput (or another package)

**Expected behavior:** Install the package

**Actual behavior:** Error (describe on the top)

### Versions

IronPython 2.7.9 (2.7.9.0) on .NET 4.0.30319.42000 (64-bit)

**Comment by slozier** [comment]
The message:
```
You are using pip version 8.1.1, however version 19.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```
is not the error message (it appears even when you do something that works). Having the actual error message would be useful in helping you out.

Without seeing the error message, my guess would be that IronPython is installed in `C:\Program Files\IronPython 2.7` and that when you are running pip install it fails to copy to the `C:\Program Files\IronPython 2.7\Lib\site-packages` folder. This occurs because you need elevated privileges to write to that folder. If this is indeed the issue you could try to run cmd as administrator. The other option is to install the package to a user folder using for example `ipy -m pip install --user pynput`.

**Comment by NaolShow** [comment]
Thank you for your answer, indeed with the cmd open as administrator the module was downloaded, so I moved the downloaded files (available here: %appdata%/Python/IronPython27/site-packages) in a folder in the searchpath of my application. But I had an error when I started the script: ImportError: No module named Xlib.display.
So Pip didn't download everything... I tried to import the library manually and I got: ImportError: No module named fcntl...

So I don't know what to do, are the modules well managed by IronPython? Thank you very much good evening!

**Comment by slozier** [comment]
`fcntl` is a Unix module which is why it does not work. I think Xlib.display does not support Windows?

Support of 3rd party packages varies, there are some known issues, for example:
1. Modules that require C extensions will now work
2. str in IronPython is equivalent to unicode instead of bytes so this may cause issues
3. sys.platform == "cli" so this may cause issues if the Python code checks for "win32"

**Comment by NaolShow** [comment]
Ok , so there isn't a complete compatibility ? :(

**Comment by slozier** [comment]
Unfortunately not, although we try to support pure Python modules as much as possible.

Closing this issue since the original problem was resolved.

**Comment by Nodirbek9204** [comment]
I am new python learner

Whey I try to install any package for ironpython I am into trouble like:
******************************************************************************
C:\Program Files\IronPython 2.7> ipy -m pip install matplotlib
Unhandled exception:
Traceback (most recent call last):
  File "C:\Program Files\IronPython 2.7\Lib\runpy.py", line 182, in run_module
  File "C:\Program Files\IronPython 2.7\Lib\runpy.py", line 107, in _get_module_
details
ImportError: No module named pip
*********************************************************************************
or next
*************************************************************************
C:\Program Files\IronPython 2.7>ipy -m ensurepip
Ignoring indexes: https://pypi.python.org/simple
Collecting setuptools
Exception:
Traceback (most recent call last):
  File "c:\users\администратор\appdata\local\temp\tmplcobae\pip-8.1.1-py2.py3-no
ne-any.whl\pip\basecommand.py", line 209, in main
    status = self.run(options, args)
  File "c:\users\администратор\appdata\local\temp\tmplcobae\pip-8.1.1-py2.py3-no
ne-any.whl\pip\commands\install.py", line 299, in run
    requirement_set.prepare_files(finder)
  File "c:\users\администратор\appdata\local\temp\tmplcobae\pip-8.1.1-py2.py3-no
ne-any.whl\pip\req\req_set.py", line 356, in prepare_files
    discovered_reqs.extend(self._prepare_file(
  File "C:\Program Files\IronPython 2.7\Lib\contextlib.py", line 35, in __exit__

    self.gen.throw(type, value, traceback)
  File "c:\users\администратор\appdata\local\temp\tmplcobae\pip-8.1.1-py2.py3-no
ne-any.whl\pip\utils\logging.py", line 36, in indent_log
    yield
KeyError: а
************************************************************************************************
or next
**********************************************************************************************
C:\Program Files\IronPython 2.7>ipy -X:Frames -m ensurepip
Ignoring indexes: https://pypi.python.org/simple
Collecting setuptools
Exception:
Traceback (most recent call last):
  File "c:\users\администратор\appdata\local\temp\tmppn5jtr\pip-8.1.1-py2.py3-no
ne-any.whl\pip\basecommand.py", line 209, in main
    status = self.run(options, args)
  File "c:\users\администратор\appdata\local\temp\tmppn5jtr\pip-8.1.1-py2.py3-no
ne-any.whl\pip\commands\install.py", line 299, in run
    requirement_set.prepare_files(finder)
  File "c:\users\администратор\appdata\local\temp\tmppn5jtr\pip-8.1.1-py2.py3-no
ne-any.whl\pip\req\req_set.py", line 356, in prepare_files
    discovered_reqs.extend(self._prepare_file(
  File "C:\Program Files\IronPython 2.7\Lib\contextlib.py", line 35, in __exit__

    self.gen.throw(type, value, traceback)
  File "c:\users\администратор\appdata\local\temp\tmppn5jtr\pip-8.1.1-py2.py3-no
ne-any.whl\pip\utils\logging.py", line 36, in indent_log
    yield
KeyError: а
*****************************************************************************************
During installation of Ironpython "pip" was selected to be installed.
I supposed pip was not installed for ironpython, after that i tried install it from local folder:

C:\Program Files\IronPython 2.7>ipy c:\pip-8.1.1-py2.py3-none-any.whl install
can't find '__main__' module in 'c:\pip-8.1.1-py2.py3-none-any.whl'
***************************************************************************************
I tried different version of pip, but no success!!!
**************************************************************************************
pip on python works very well, packades are easely installing, problem only with ironpython.
also, I tried different verisons of ironpython, no positiv result. Can any body halp me? Please!!!!




CMD runed as a admin
Windows 7   64 bit


**IronPython version:**
 C:\Program Files\IronPython 2.7>ipy -V
IronPython 2.7.9 2.7.9.0 on .NET 4.0.30319.42000

**python version**
c:\>py -V
Python 3.5.2

**pip verson on python**
c:\>py -m pip -V
pip 8.1.1 from C:\Program Files\Python35\lib\site-packages (python 3.5)

**pip version on ipy**
C:\Program Files\IronPython 2.7>ipy -m pip -V
Unhandled exception:
Traceback (most recent call last):
  File "C:\Program Files\IronPython 2.7\Lib\runpy.py", line 182, in run_module
  File "C:\Program Files\IronPython 2.7\Lib\runpy.py", line 107, in _get_module_
details
ImportError: No module named pip
