### ISSUE TITLE
Custom sys.excepthook is ignored by IronPython

### ISSUE THREAD

**Issue by avli** [IronLanguages/ironpython2#654]
### Description

The `sys.excepthook` hook seems to be ignored by IronPython.

### Steps to Reproduce

Run the following code with IronPython 2.7.9:

```python
import sys


def excepthook(exctype, value, tb):
    print "in excepthook()"


sys.excepthook = excepthook


1 / 0
```

**Expected behavior:** "in excepthook()" is printed.

**Actual behavior:** the default exception hook is run.

### Versions

IronPython 2.7.9 2.7.9.0 on .NET 4.0.30319.42000.

**Comment by slozier** [comment]
Seems to work in the interpreter, but not when running as a script.

**Comment by avli** [comment]
Thanks a lot!
