### ISSUE TITLE
ElementTree / expat parser loses data when parsing 8192 or more characters in an element

### ISSUE THREAD

**Issue by chriscampetti** [IronLanguages/ironpython2#655]
Windows 10
IronPython 2.7.9 (2.7.9.0) on .NET 4.0.30319.42000 (64-bit)

ElementTree is losing data when parsing strings like `<Data>somedata</Data>` where "somedata" is 8192 characters or more.
Digging into some private fields and disabling buffering (set to 8192 [here](https://github.com/IronLanguages/ironpython2/blob/4355f807916f9f0de1c25030fa06b56028850e5a/Src/IronPython.Modules/pyexpat.cs#L248)?) seems to work around the problem.

Can be reproduced with this script:
```


import xml.etree.ElementTree as ET

for count in (8191, 8192):
    s = '<Data>' + ('1'*count) + '</Data>'
    elem = ET.fromstring(s)
    result_len = len(ET.tostring(elem))
    string_len = len(s)
    #Count will include the 13 characters of '<Data>' and '</Data>'
    print '{}, {}, {}'.format(result_len, string_len, result_len == string_len)

#Disabling buffering works around it:
for count in (8191, 8192):
    s = '<Data>' + ('1'*count) + '</Data>'
    parser = ET.XMLParser()
    parser._parser.buffer_text = False
    elem = ET.fromstring(s, parser=parser)
    result_len = len(ET.tostring(elem))
    string_len = len(s)
    print '{}, {}, {}'.format(result_len, string_len, result_len == string_len)

```
Output:
```
8204, 8204, True
8, 8205, False
8204, 8204, True
8205, 8205, True
```

**Comment by slozier** [comment]
Thanks for the bug report!

**Comment by chriscampetti** [comment]
Thanks! Do you know if this would wind up in a 2.7.10 release (if there is a 2.7.10, I see there was an alpha release)?

**Comment by slozier** [comment]
Yes, it'll be in the 2.7.10 release which I hope to do once .NET Core 3.0 is released.
