### ISSUE TITLE
sys.version is not set in hosted runtimes

### ISSUE THREAD

**Issue by tinyg** [IronLanguages/ironpython2#672]
### Description

In the latest source, the sys.version property is not set when running in a runtime created programmatically (as opposed to ipy.exe)

### Steps to Reproduce

1. Using LINQpad (or .net project) add source and run:

```
var code = 
@"
import sys
print sys.version";

var _engine = IronPython.Hosting.Python.CreateEngine();

var runtime = _engine.Runtime;
var scope = _engine.CreateScope();

var source = _engine.CreateScriptSourceFromString(code, SourceCodeKind.AutoDetect);
source.Execute(scope);
```

**Expected behavior:** [What you expected to happen]

2.7.10a1 (2.7.10.0001)\n[.NETFramework,Version=v4.5 on .NET Framework 4.7.3324.0 (64-bit)]

(or similar) is shown

**Actual behavior:** [What actually happened]

None

is shown

### Versions

2.7.10a1 (2.7.10.0001)\n[.NETFramework,Version=v4.5 on .NET Framework 4.7.3324.0 (64-bit)]

(appears to be anything after #622 )

**Comment by slozier** [comment]
Thanks! This one should be fixed by https://github.com/IronLanguages/ironpython2/pull/670
