### ISSUE TITLE
exit() broken in ipy.exe

### ISSUE THREAD

**Issue by tinyg** [IronLanguages/ironpython2#673]
### Description

When using ipy.exe, the "exit()" function does not work - I have to kill the process.

### Steps to Reproduce

1. Start "ipy.exe"
2. Type "exit()"

**Expected behavior:** [What you expected to happen]

ipy.exe quits

**Actual behavior:** [What actually happened]

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'exit' is not defined

### Versions

IronPython 2.7.10 (2.7.10.0) on .NET 4.0.30319.42000 (64-bit)

**Comment by tinyg** [comment]
Tested this against the 2.7.10a0 release and its broken there

**Comment by slozier** [comment]
`exit` is defined in `site.py` which is part of the standard library and loaded automatically (if available) when launching the console. Was the standard library available (e.g. does something like `import csv` work). If not you can set the IRONPYTHONPATH variable to point to it?

I think it used to be picked up from `Src\IronPython\Lib` and was copied to the `bin\Lib` folder, but this is no longer the case. Might be worth adding the file to `IronPython.csproj` to get it to copy to the `bin\Lib` folder again...

**Comment by slozier** [comment]
Ran some tests, and it looks like if I bring in the `site.py` file I also have to bring in a bunch of other dependencies so I guess it's better to leave it out of `IronPython.csproj`.

**Comment by tinyg** [comment]
Ah - yep - adding the standard lib seems like it fixes it.

**Comment by tinyg** [comment]
Just thinking about this - maybe you should get some kind of error at startup if it can't find mandatory standard lib stuff?

Its very confusing as it stands...

Even if it just said "Loading Standard Library from ...." or "Could not find standard library" then you'd get some indicator that things were broken or fine

**Comment by slozier** [comment]
Well, in theory the standard library is not mandatory to run Python 2, although it may not work very well without it. We could do like CPython and throw an `ImportError: No module named site` if launching `ipy` without `site.py`. But, it might break some hosted scenarios which don't need the standard lib? Would need to look into it...

**Comment by tinyg** [comment]
Seems like exit(), help() etc is pretty important for the console app 🙂 I was more just thinking of an extra banner line that told you what the current library path was (and maybe whether it exists)

**Comment by slozier** [comment]
Unfortunately the import mechanism is somewhat more complicated than just having a single library path. In any case, this is something of a non-issue for normal users (that use the installer or another release package) since the library is never missing (unless they mess with their installation).

**Comment by tinyg** [comment]
ok - well maybe another option would be to implement the -v switch?

On CPython, doing ```python -v``` shows:

```
C:\Temp\net45>python -v
# installing zipimport hook
import zipimport # builtin
# installed zipimport hook
# C:\Users\chris.smith\.windows-build-tools\python27\lib\site.pyc matches C:\Users\chris.smith\.windows-build-tools\pyth
on27\lib\site.py
import site # precompiled from C:\Users\chris.smith\.windows-build-tools\python27\lib\site.pyc
# C:\Users\chris.smith\.windows-build-tools\python27\lib\os.pyc matches C:\Users\chris.smith\.windows-build-tools\python
27\lib\os.py
import os # precompiled from C:\Users\chris.smith\.windows-build-tools\python27\lib\os.pyc
import errno # builtin
import nt # builtin
# C:\Users\chris.smith\.windows-build-tools\python27\lib\ntpath.pyc matches C:\Users\chris.smith\.windows-build-tools\py
thon27\lib\ntpath.py
...
```

whereas ipy just shows the regular banner and prompt...

I just used the release zip file to test so it can happen easily in the release package...

**Comment by tinyg** [comment]
And

```
MAIN  9:19:50 C:\TFS\Platform.Core\main.dev>python -v
# installing zipimport hook
import zipimport # builtin
# installed zipimport hook
ImportError: No module named site
....
```

as you say when site.py is not available

**Comment by tinyg** [comment]
You can still do ```python -S``` to run without ```import site```

**Comment by tinyg** [comment]
Also ```exit()``` still works even without site loaded :innocent:

**Comment by tinyg** [comment]
actually - just tested again and I'm wrong about that - once you do ```python -S``` then exit doesn't work.

**Comment by slozier** [comment]
@tinyg Hmm, just downloaded IronPython.2.7.10-alpha0.zip, unzipped, ran ipy.exe and everything works fine. Can you let me know what steps you used to reproduce the issue with the release package?

Yes, it does seem like `-v` functionality is missing. Although it does set the sys.flags.verbose value to 1 that doesn't seem to trigger any extra logging.

**Comment by tinyg** [comment]
Maybe you had an environment variable set for your python libraries?

For me, if I just unzip the package and then go into the net45 folder and run ipy.exe I see the behaviour.
