### ISSUE TITLE
Problem with importing modules from Zip archive

### ISSUE THREAD

**Issue by AlexSeredenko** [IronLanguages/ironpython2#675]
Import modules from Zip archive which contains subfolders names with dots doesn't work

```
import sys
sys.platform="win32"

sys.path.append("C:\Data\scapy-2.4.2.zip\scapy-2.4.2")

from scapy.all import *
```
**Actual behavior:** 
ImportError: No module named scapy.all

In case of renaming folder "scapy-2.4.2" to "scapy" inside zip import works correctly

### Versions

2.7.9.

**Comment by slozier** [comment]
I assume this is the zip from https://github.com/secdev/scapy/releases? CPython is giving me the same failure. I assume there's something "bad" with the zip file since recreating the zip file with the same content fixes the issue.

**Comment by AlexSeredenko** [comment]
It's a zip created by Python setup function.
CPython works correctly with this zip.
I guess the problem is replacing dots to DirectorySeparatorChar in method "MakeFilename" class "zipimporter".
https://github.com/IronLanguages/ironpython2/blob/master/Src/IronPython.Modules/zipimport.cs

**Comment by slozier** [comment]
CPython does the same thing in [make_filename](https://github.com/python/cpython/blob/2.7/Modules/zipimport.c). I was also able to do the import using a folder within the zip file with dots (although it crashes due to https://github.com/IronLanguages/ironpython2/issues/653).

Could you upload your zip file?

**Comment by AlexSeredenko** [comment]
```
    strcpy(path, prefix);
    strcpy(path + len, name);
    for (p = path + len; *p; p++) {
        if (*p == '.')
            *p = SEP;
    }
```
as I see cpython replace dots only in name, the cylce begins from "p = path + len" whereas IronPython replace full path (prefix + name).Replace('.', Path.DirectorySeparatorChar);

**Comment by slozier** [comment]
Ah right, I'm an idiot. I had scapy in my site-packages and it was picking that up. 😩 

Just need to drop the parentheses in that case.
