### ISSUE TITLE
IronPython.Runtime.Exceptions.ImportExceptions: No module name job 

### ISSUE THREAD

**Issue by davideveloper** [IronLanguages/ironpython2#684]
If anyone could help me, I would appreciate it. I am running some Python codes from .NET which sends to call the Software - Autodesk Revit, it happens that when it is starting it sends me the Error 'IronPython.Runtime.Exceptions.ImportExceptions: No module name job'.

I have tried to verify the Python versions installed to see if I am wrong about something but it has the same error, I tried to make a Debug in my .NET code to verify if something I am not sending but I cannot find the cause.

They could support me.

![image](https://user-images.githubusercontent.com/7434352/68418674-4c7c7580-015e-11ea-80c7-65367775c4b7.png)

**Comment by slide** [comment]
Do you have a job.py or job\__init__.py somewhere? Is that path in the search paths for the IronPython engine you are using? This error means that IronPython can't find the job module to import.
