### ISSUE TITLE
Hello, I checkedout the latest ironpython2 source from github repo. while building the ironPython.sln source code in visual studio 2019. I am unable to load project files and it throws an error and not able to access any file. Any solution to this?

### ISSUE THREAD

**Issue by RaviMDhoble** [IronLanguages/ironpython2#689]
### Prerequisites

The issue tracker is used to report bugs and request new features, NOT to ask questions.

Questions should be posted to the users mailing list which can be accessed at 
https://ironpython.groups.io/g/users. 

* [ ] Are you running the latest version?
* [ ] Are you reporting to the correct repository?
* [ ] Did you perform a cursory search?

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

You can get this information from executing `ipy -V`.

**Comment by slozier** [comment]
1. Ensure you have installed the latest .NET Core SDK
2. Remove the global.json file (which may be pointing to older an SDK version which is not installed)

**Comment by RaviMDhoble** [comment]
Thank you @slozier for providing a solution. It worked. 1. Yes, I have lasted .NET core SDK installed.
2. Removing global.json helped to load .cs files and other files in VS2019 and i can see them in Solution Explorer. 
Now, another issue came related to missing project dependencies. When I am trying to build the project. It is showing a lot much error related above reason and failed to build. I tried a couple of ways to resolve that issue but didn't help. Can you tell me what causes this and possible solution?. For your reference, I have attached sample screenshots. 
[IronPython2_Build Issue.txt](https://github.com/IronLanguages/ironpython2/files/4087015/IronPython2_Build.Issue.txt)
![Issue2_1](https://user-images.githubusercontent.com/55841229/72741654-1764b880-3bce-11ea-99d0-27409fd6987c.PNG)
![Issue2_2](https://user-images.githubusercontent.com/55841229/72741655-1764b880-3bce-11ea-9fe0-9cfd6813730b.PNG)
![Issue2_3](https://user-images.githubusercontent.com/55841229/72741656-1764b880-3bce-11ea-86f8-b5b8c331f13f.PNG)

**Comment by slozier** [comment]
You also need to clone the DLR submodule: `git submodule update --init`

**Comment by RaviMDhoble** [comment]
Thanks @slozier, It worked. The project build is successful.
![IronPythonn_buildSuccess](https://user-images.githubusercontent.com/55841229/72780359-aca29400-3c44-11ea-8d73-88f34f023bb1.PNG)
