### ISSUE TITLE
some words can not be replaced in MS Word file template for some row record in window 7

### ISSUE THREAD

**Issue by slide** [IronLanguages/ironpython2#69]
_From @hoyeunglee on March 10, 2017 8:1_

i use these code with ironpython with the same template,
first row record it has missing field which can not be replaced and one or two record has missing to replace
and checked that it has value shown in console

i had already delay 3 seconds , is it MSWORD problem? why some files succeed but why can not?

```
import sys
import clr
import csv
import os
import System
from System import DateTime
import time
    
clr.AddReference("Microsoft.Office.Interop.Word")
import Microsoft.Office.Interop.Word as Word

def doc_replace_text(source_filename, tokens, values, destination_filename):

    missing = System.Type.Missing
    replaceAll = Word.WdReplace.wdReplaceAll

    word_application = Word.ApplicationClass()
    word_application.visible = False

    document = word_application.Documents.Open(source_filename)

    for i in range(len(tokens)):
        for r in document.StoryRanges:
            #print "i = %d, tokens[i] = %s, values[i] = %s" % (i, tokens[i], values[i])
            r.Find.Text = tokens[i]
            r.Find.Replacement.Text = values[i]
            r.Find.Wrap = Word.WdFindWrap.wdFindContinue
            r.Find.Execute(missing, missing, missing, missing, missing, missing, missing, missing, missing, missing, replaceAll, missing, missing, missing, missing)
            
    time.sleep(3)
    document.SaveAs(destination_filename)
    document.Close()
    document = None

    word_application.Quit()
    word_application = None



def main():
    print("main")

if __name__ == "__main__":
    main()
    currentworkingdirectory = str(os.getcwd()).replace("\\","\\")
    iserror = False
    headervalues = []
    with open(str(currentworkingdirectory)+"\\newusers.csv", 'rb') as csvfile:
        reader = csv.reader(csvfile)
        headersource = reader.next()

    headersource.remove('initial password')
    headersource.remove('userType')

    header = []
    for headerm in headersource:
        header.append("[" + headerm + "]")

    linenumber = 0
    with open(str(currentworkingdirectory)+"\\newusers.csv", 'rb') as csvfile:
        reader = csv.DictReader(csvfile)
        print(header)
        for row in reader:
            notvalidfield = False
            linenumber = linenumber + 1
            for hh in headersource:
                if len(row[hh].strip()) <= 0:
                    notvalidfield = True
            if notvalidfield == True:
                print("line number " + str(linenumber) + " one of field is empty")
            if iserror == False and notvalidfield == False:
                try:
                    for hh in headersource:
                        headervalues.append(row[hh].strip())
                    for hh in headersource:
                        print(hh+":" + row[hh].strip())
                    doc_replace_text(str(currentworkingdirectory)+"\\Application Form.doc", header, headervalues,str(currentworkingdirectory)+"\\Application Form "+row['company'].strip()+".doc")
                    time.sleep(2)
                    headervalues = []
                except:
                    print "Unexpected error:", sys.exc_info()[0]
                    iserror = True


```

_Copied from original issue: IronLanguages/main#1588_

**Comment by slide** [comment]
Can you upload an example word doc?

**Comment by hoyeunglee** [comment]
Company document is not allowed to upload, it is a registration form document, I guess many people will meet this issue if they tried. I am not sure whether the version of MSWord cause this problem, I used c# directly. Perhaps I can record a video with iPhone and send a link later

**Comment by hoyeunglee** [comment]
https://drive.google.com/file/d/0Bxs_ao6uuBDUa1NxMXFSQTZUN0E/view?usp=sharing

you can watch this video

**Comment by hoyeunglee** [comment]
please tell me that you watched, then i can delete this link

**Comment by slide** [comment]
You can remove it

**Comment by hoyeunglee** [comment]
i removed

**Comment by slide** [comment]
I really don't think this is specific to IronPython though.

**Comment by hoyeunglee** [comment]
do not know why some fields can not be replaced, different row of records has different result, some fields can be replaced but not all

**Comment by slide** [comment]
Without a way to reproduce, it will be pretty hard to help at all

**Comment by slozier** [comment]
Probably not the issue (didn't see the video), but the sample code only worked for me once I replaced `r.Find.Execute(missing, missing, missing, missing, missing, missing, missing, missing, missing, missing, replaceAll, missing, missing, missing, missing)` with `r.Find.Execute(Replace=replaceAll)`

**Comment by hoyeunglee** [comment]
https://drive.google.com/file/d/0Bxs_ao6uuBDUYl9EUEVkcVY1YkE/view?usp=sharing

using this syntax , r.Find.Execute(Replace=replaceAll)
it works,
thank you very much.

**Comment by hoyeunglee** [comment]
slozier, if you watched , please tell me , so that i can remove the link

**Comment by slozier** [comment]
@hoyeunglee Yes you can remove it.

**Comment by hoyeunglee** [comment]
i find the microsoft web site, https://msdn.microsoft.com/en-us/library/office/ff193977.aspx
it really use 11th parameter as replaceAll, it seems code from googled correct

**Comment by slide** [comment]
In the future, please all questions likes this on the users mailing list at users@ironpython.groups.io
