### ISSUE TITLE
Redirecting only stdout to `os.devnull` with subprocess causes error in stderr

### ISSUE THREAD

**Issue by pekkaklarck** [IronLanguages/ironpython2#702]
The problem is demonstrated below. It doesn't occur if stderr is redirected to DEVNULL (or perhaps the exception is just swallowed in that case). With CPython there are no problems.

```
IronPython 2.7.9 (2.7.9.0) on .NET 4.0.30319.42000 (64-bit)
Type "help", "copyright", "credits" or "license" for more information.
>>> from subprocess import Popen, PIPE
>>> import os
>>> DEVNULL = open(os.devnull, 'w')
>>> p = Popen(['python', '-c', 'print("hi")'], stdout=DEVNULL, stderr=PIPE)
>>> print p.stdout
>>> print p.stderr.read()
close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr
```

**Comment by slozier** [comment]
@pekkaklarck I'm not able to reproduce the issue over here. I get the following output:
```
IronPython 2.7.9 (2.7.9.0) on .NET 4.0.30319.42000 (64-bit)
Type "help", "copyright", "credits" or "license" for more information.
>>> from subprocess import Popen, PIPE
>>> import os
>>> DEVNULL = open(os.devnull, 'w')
>>> p = Popen(['python', '-c', 'print("hi")'], stdout=DEVNULL, stderr=PIPE)
>>> print p.stdout
None
>>> print p.stderr.read()

>>>
```
Are you sure the exception message is it not coming from `python`?

**Comment by pekkaklarck** [comment]
The error probably comes from the executed `python`. I don't get it when I run the same code with CPython or Jython, so I thought it has something to do with IronPython. Since you don't get it, it may be due to something else. I can try to debug it further.

**Comment by slozier** [comment]
Closing since I'm not able to reproduce the issue, feel free to re-open if you have any more info.
