### ISSUE TITLE
StackOverflowException - Calling function returning dict

### ISSUE THREAD

**Issue by jpatel107** [IronLanguages/ironpython2#704]
Calling a function from python script file from C#. If python function is returning a dict object, C# side fails with StackOverflowException. Here is the script and call from C#.

-----iPython Script----
import math
def stats(values):
  odict = {}
  odict['max'] = max(values)
  odict['min'] = min(values)
  odict['sum'] = sum(values)
  return odict

-------C# Code---------
ScriptEngine _Engine = Python.CreateEngine();
ScriptScope scope = _Engine.CreateScope();
_Engine.ExecuteFile(@"C:\temp\iScript.py", scope);

double[] dArr = new double[10] {23.3, 34, 45.6, 45.4, 34.6, 4.4, 5.7, 9.8, 4.3, 99.3};
dynamic func = scope.GetVariable("stats");
var resultDict = func(dArr);    //this throws StackOverflowException 

////Exception Details////////
System.StackOverflowException   HResult=0x800703E9  Message=Exception of type 'System.StackOverflowException' was thrown.

**Comment by slozier** [comment]
I am not able to reproduce this with the provided sample, it works fine for me.

**Comment by jpatel107** [comment]
Thank you for quickly looking into this. I found the issue. It was script issue where there was another method called max which was also using math.max without namespace. This was causing max used in stats function to go into infinite loop of calling this method over and over instead of using math.max. Thanks you again for quickly trying this out.

def max(values):
  res = max(values)
  return res
