### ISSUE TITLE
Error Importing C# dll in ironPython

### ISSUE THREAD

**Issue by darkjhesus** [IronLanguages/ironpython2#707]
Dear, I wrote the basic library showed below, then, create the dll and import in IronPython with clr, but I recieve the problem showed in the attached file. Why is this error.
![Sin título](https://user-images.githubusercontent.com/18389488/82070982-1256d800-969b-11ea-959b-5e5b076f27db.png)

using System;

namespace ClassLibrary1
{
    public class Class1
    {
        public void Connect(int x, int y)
        {
            Console.WriteLine(x + y);
        }
    }
}

**Comment by slozier** [comment]
You need to instantiate your class (same as you would need to do in C#):
```Python
cpp.Class1().Connect(4,5)
```

**Comment by darkjhesus** [comment]
Thanks a lot for your help...
