### ISSUE TITLE
`io.BytesIO` inheritance class wrong number of ctor args

### ISSUE THREAD

**Issue by fastmutex** [IronLanguages/ironpython2#711]
### Prerequisites

* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?

### Description

IronPython 2.7.10 fails to call the ctor for class that inherits `io.BytesIO`

I'm creating a stream class the inherits `io.BytesIO` as follow: 

### Steps to Reproduce

```
import io
class TestStream(io.BytesIO)
    def __init__(self, val1, val2, val3):
        print('TestStream.__init__')
def test():
    testObject = TestStream('val1', 'val2', 'val3')
test()
```
**Expected behavior:** 

No exception thrown

**Actual behavior:** 

Exception thrown
`TypeError: TestStream() takes at most 2 arguments (4 given)`

### Versions
IronPython 2.7.10

**Comment by slozier** [comment]
Thanks for the report!
