### ISSUE TITLE
pip failing to install libraries

### ISSUE THREAD

**Issue by isaiahfisher** [IronLanguages/ironpython2#714]
### Description

Whenever I try to use pip with my installation of IronPython2.7.10 I receive this error stack:

![image](https://user-images.githubusercontent.com/13983125/83059860-92c8f180-a028-11ea-9dcd-ef31770e650e.png)

Here is my dotnet information:
![image](https://user-images.githubusercontent.com/13983125/83059942-b12eed00-a028-11ea-9edd-3200bb5acce1.png)

I have so far been unable to figure out why the IronPython pip seems to fail.

### Steps to Reproduce

1. Install IronPython
2. Try to use pip in order to install a package
3. The Above error occurs

**Expected behavior:** pip successfully installs a package

**Actual behavior:** failure with several errors

### Versions

![image](https://user-images.githubusercontent.com/13983125/83060128-fbb06980-a028-11ea-9b79-3301a72b6b3c.png)

**Comment by slozier** [comment]
Looks like an issue with `str` being `unicode` instead of `bytes` with IronPython. Since all this occurs in 3rd party libraries there's not much we can do about it. I would suggest not upgrading pip to the latest version and using one that comes with the release.

**Comment by isaiahfisher** [comment]
Is there a way to quickly or easily revert? I think the reason I upgraded in the first place was due to this issue as an attempt to fix it, but I will try the original version.

**Comment by slozier** [comment]
Hmm, you can delete the `Lib\site-packages` then run `ipy -m ensurepip` to reinstall.

**Comment by isaiahfisher** [comment]
This is now the output I am receiving:

![image](https://user-images.githubusercontent.com/13983125/83064861-821c7980-a030-11ea-963f-ec1c7d9a2e0c.png)

**Comment by isaiahfisher** [comment]
Could my version of setuptools be broken? I was able to install pip fine, but I cannot use it on nltk

**Comment by slozier** [comment]
This is the issue noted at https://github.com/IronLanguages/ironpython2/issues/624. Unfortunately I don't have a good solution beyond manually patching `__init__.py` as follows:
```Python
del __metaclass__

class Command(_Command):
    # ...

__metaclass__ = type
```

I did try pip installing `nltk` after this patch but just ran into other issues.

**Comment by isaiahfisher** [comment]
@slozier do you know if this issue exists in prior versions of IronPython? My use case of IronPython is almost entirely NLTK support related. If you happen to find some solution to install NLTK I would be appreciative!

**Comment by slozier** [comment]
@isaiahfisher It looks like this particular failure isn't present with 2.7.9, however `nltk` fails to install when it tries to compile the `regex` module. This is appears to be a C extension module and will unfortunately not work with IronPython.

**Comment by isaiahfisher** [comment]
@slozier ok thank you. The NLTKNet wrapper listed this as a dependency in its project. I will see if I cannot self patch it or revert to a previous version and fix it. I will update this issue with a solution if I find one!

**Comment by slozier** [comment]
@isaiahfisher I was able to `pip install nltk==3.4` with IronPython 2.7.9.

**Comment by isaiahfisher** [comment]
@slozier thank you for the info! I appreciate the help! Sorry to take so much time on what amounts to a support issue rather than a bug in IronPython itself.

**Comment by slozier** [comment]
No problem, in a way it's a bug with IronPython as upgrading the version of setuptools with 2.7.10 broke pip install for some packages.

**Comment by slozier** [comment]
I think I've managed to resolve the pip install issues on master. Closing this.
