### ISSUE TITLE
IronPython 2.7.10 installed half disfunctional and inconsistent with VS2019

### ISSUE THREAD

**Issue by Hale812** [IronLanguages/ironpython2#718]
- The current IronPython distributive is not consistent with VisualStudio 2019, and useless for quick start, or studying IronPython, and following manuals, and textbooks.
- Some advanced installation is required, which is not covered in installation instructions.

This contradicts the official literature and manuals on IronPython

### Prerequisites

1. Install Visual Studio 2019 Community Edition "with Python" distribution on Windows x64 system, **clean of any development tools.** I repeat, no other development tools, which would alleviate or worsen the situation. Default config.
2. Install IronPython-2.7.10.msi, default config.

* [Y] Are you running the latest version?
* [Y] Are you reporting to the correct repository?
* [Y] Did you perform a cursory search?

### Description

REPL and basic packages essential for quick start, and studying by the book are not available after installation in 64-bit environment, and no directions are given to advanced installation at the official website and distribution:

### Steps to Reproduce
1. Start VS 2019 and create an "IronPython Applocation" project
2. Add IronPython 2.7 (64 bit) environment (working in x64 OS), make it active and remove 32-bit environment.
3. Go to interactive Python console (Alt+I), and change environment to IronPython (x64)
4. Type "import clr". 
A)    Error appears in the Interactive console:
> >>> import clr
> Error using selected REPL back-end:
> IPython mode requires IPython 0.11 or later: No module named IPython
> Using standard backend instead
> 
5. type "2+2"
The same as above ERROR (A) appears
6.  Go to Python Environments -> Search PyPI and installed packages. Type there IPython.
7. Select Install ipython
B) Another error appears:

> ----- Installing 'ipython==7.15.0' -----
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> AttributeError: 'module' object has no attribute 'main'
> ----- Failed to install 'ipython==7.15.0' -----
> 
> 
8. type  "ipy -V" in the interactive console
C) Adnother Error appears:

> Error using selected REPL back-end:
> IPython mode requires IPython 0.11 or later: No module named IPython
> Using standard backend instead
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> NameError: name 'ipy' is not defined
> 
> 

**Expected behavior:** [What you expected to happen]
REPL should be installed, pre configured, and function after VS2019 and IronPython installation, and creating an IronPython project (any, x64, or not).

**Actual behavior:** [What actually happened]
Errors (A) (B), and (C) appear, demonstrating semi-dysfunctional state of IronPython installation.
In addition Developer PowerShell is filled with a red garbage:

> `Import-Module : ファイルまたはアセンブリ 'file:///C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\Microsoft.VisualStudio.DevShe
> ll.dll'、またはその依存関係の 1 つが読み込めませんでした。このアセンブリは現在読み込まれているランタイムより新しいランタイムでビルドされているため、読み込
> むことができません。
> 発生場所 行:1 文字:18
> + & { Import-Module <<<<  $env:VSAPPIDDIR\..\Tools\Microsoft.VisualStudio.DevShell.dll}; Enter-VsDevShell -SkipAutomaticLocation -SetDefaultWindowTitle -In
> stallPath $env:VSAPPIDDIR\..\..\
>     + CategoryInfo          : NotSpecified: (:) [Import-Module]、BadImageFormatException
>     + FullyQualifiedErrorId : System.BadImageFormatException,Microsoft.PowerShell.Commands.ImportModuleCommand
> 
> 用語 'Enter-VsDevShell' は、コマンドレット、関数、スクリプト ファイル、または操作可能なプログラムの名前として認識されません。名前が正しく記述されている こと
> を確認し、パスが含まれている場合はそのパスが正しいことを確認してから、再試行してください。
> 発生場所 行:1 文字:98
> + & { Import-Module $env:VSAPPIDDIR\..\Tools\Microsoft.VisualStudio.DevShell.dll}; Enter-VsDevShell <<<<  -SkipAutomaticLocation -SetDefaultWindowTitle -In
> stallPath $env:VSAPPIDDIR\..\..\
>     + CategoryInfo          : ObjectNotFound: (Enter-VsDevShell:String) []、CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
> `

Despite forced English environment, these strings are in wrong Japanese locale, and originaly non-readable in the console.
Probably, it originates from **unchangeable** Windows7 installation locale, which is Japanese, but should be overiden in VisualStudio.
Approximate translation is as follows:
", Or one of its dependencies could not be loaded. This assembly was built with a newer runtime than the one currently loaded, so can not be used. Occurrence line: 1 character: 18

The word 'Enter-VsDevShell' is not recognized as the name of a cmdlet, function, script file, or operable program. Make sure the name is written correctly, and if the path is included, make sure the path is correct and try again.
  Occurrence line: 1 character: 98

### Versions
ipy -V can not be executed from Interactive console
The version displayed at console initialization: IronPython 2.7 (64-bit) interactive window [PTVS 16.6.20100.1-16.0]
Microsoft Visual Studio Community 2019 Version 16.6.2
VisualStudio.16.Release/16.6.2+30204.135
Microsoft .NET Framework Version 4.8.03761

**Comment by Hale812** [comment]
Additional information.

Switching to default 32-bit environment allows loading clr.
... But we are living in 64-bit world today, right. It could be 16 bit, or 8-bit Python, but today's requirements are 64bit applications with a straight 64-bit heap, right?
Developer console keeps throwing the same errors.

**Comment by slozier** [comment]
Visual Studio issues should probably be filed at the PTVS repo: https://github.com/microsoft/PTVS instead.

That being said, looking at the error messages you're getting it seems like you are trying to use the IPython interactive mode which is not supported with IronPython (see https://github.com/Microsoft/PTVS/issues/84 and https://docs.microsoft.com/en-us/visualstudio/python/interactive-repl-ipython?view=vs-2019).

You can turn it off in the Python Environments window:
![image](https://user-images.githubusercontent.com/6061329/85730050-54762f00-b6c7-11ea-9dbb-30bad354cfb0.png)

**Comment by Hale812** [comment]
>Visual Studio issues should probably be filed at the PTVS repo:
There are no issues with VS. The issue is with Python, which is not well adjoined to VS2019 after installation. Particularly the 64bit components.

>e IPython interactive mode which is not supported with IronPython
Why isn't it supported? Shouldn't it be? Why is it supported in 32 bits, and not supported in 64 bits?
I do not say it may not be used. I don't know.
But the installer does not configure it in a way sufficient for immediate use and studying. Some advanced configuration/installation is needed.

>You can turn it off 
But I need it! It is one of key functions aggressively advertised almost in every paper and the Foord's book.

**Comment by slozier** [comment]
Perhaps there is a misunderstanding here. Is the issue with IPython or with the interactive window?

Error A:
> Error using selected REPL back-end:
IPython mode requires IPython 0.11 or later: No module named IPython
Using standard backend instead

This is because **IPython interactive mode** is not supported on IronPython (this is clearly stated in the VS documentation https://docs.microsoft.com/en-us/visualstudio/python/interactive-repl-ipython?view=vs-2019). You can ignore the error message and keep using the interactive window. If you do not want to see the error message then turn off the IPython interactive mode (as shown in the screenshot above).

As for why IPython mode is not supported, it's because it does not work with IronPython. There are some incompatibilities in some of the 3rd party libraries used by IPython.

Error B:
> ----- Installing 'ipython==7.15.0' -----
Traceback (most recent call last):
File "", line 1, in
AttributeError: 'module' object has no attribute 'main'
----- Failed to install 'ipython==7.15.0' -----

It does appear that pip does not work in Visual Studio. I will have to look into this. However, as I mentioned, even if pip install ipython did succeed, IPython would not work.

Error C:
> Error using selected REPL back-end:
IPython mode requires IPython 0.11 or later: No module named IPython
Using standard backend instead
Traceback (most recent call last):
File "", line 1, in
NameError: name 'ipy' is not defined

I do not see the issue here, other than the IPython warning (see Error A), this is exactly the error you should see if you typed `ipy -V` in the interpreter.

**Comment by Hale812** [comment]
Ok, I got it, it is a special knowledge, not available to people who just opened the book, and downloaded IronPython with VS2019. As I said advanced manipulations are required, and there are thousands of reasons for any thing to not work.

But it does not change the fact that 32 bit version is installed correctly with the Interactive Console working 100%. And 64 bit version is not.

Can you just give a simple answer, why it works with 32 bit interpreter, and how to configure 64bit interpreter the same way? And then could you kindly implement this in installer, as it should be?

**Comment by slozier** [comment]
> But it does not change the fact that 32 bit version is installed correctly with the Interactive Console working 100%. And 64 bit version is not.

IronPython does not install anything in Visual Studio. All IronPython integration in Visual Studio is done by PTVS (https://github.com/microsoft/PTVS).

> Can you just give a simple answer, why it works with 32 bit interpreter, and how to configure 64bit interpreter the same way? And then could you kindly implement this answer in installer?

As per the above answer, this is all done in PTVS so I have no idea why the default settings for the 32-bit interpreter would be different than the 64-bit interpreter. Because PTVS is part of Visual Studio (and not IronPython) there's nothing I can change in the installer to resolve this issue.

**Comment by Hale812** [comment]
OK, that is really amazing. I had an impression that everything is designed with Microsoft's participation transparently with shared design rules and roadmap. So I will move there.

**Comment by slozier** [comment]
Unfortunately Microsoft stopped contributing to IronPython in 2010.

**Comment by Hale812** [comment]
closing the issue since moving it to PTVS
