### ISSUE TITLE
Unable to import CLR types from System.dll

### ISSUE THREAD

**Issue by kellyelton** [IronLanguages/ironpython2#722]
### Description

Can't import from System.dll.

Exception : 

> "Cannot import name Directory" | IronPython.Runtime.Exceptions.ImportException
>    at IronPython.Runtime.Importer.ImportFrom(CodeContext context, Object from, String name)
>    at IronPython.Runtime.Operations.PythonOps.ImportFrom(CodeContext context, Object module, String name)
>    at Microsoft.Scripting.Interpreter.FuncCallInstruction`4.Run(InterpretedFrame frame)
>    at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
>    at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
>    at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
>    at IronPython.Compiler.PythonScriptCode.Run(Scope scope)
>    at IronPython.Compiler.RuntimeScriptCode.InvokeTarget(Scope scope)
>    at IronPython.Compiler.RuntimeScriptCode.Run(Scope scope)
>    at Microsoft.Scripting.SourceUnit.Execute(Scope scope, ErrorSink errorSink)
>    at Microsoft.Scripting.SourceUnit.Execute(Scope scope)
>    at Microsoft.Scripting.Hosting.ScriptSource.Execute(ScriptScope scope)
>    at Microsoft.Scripting.Hosting.ScriptEngine.Execute(String expression, ScriptScope scope)

### Steps to Reproduce

1. Create a dotnet core wpf application
2. Create PythonEngine `var engine = Python.CreateEngine();`
3.  Create scope `var scope = engine.CreateScope();`
4.  Run script `engine.Execute("from System.IO import Directory", scope);`
5. Exception should be thrown

**Expected behavior:**
Expect to be able to import System.dll and use the types

**Actual behavior:**
Exception

### Versions
Iron Python: 2.7.10
dotnet core wpf app: 3.1

**Comment by kellyelton** [comment]
Calling ` engine.Runtime.LoadAssembly(typeof(System.IO.Directory).Assembly);` before works.

**Comment by slozier** [comment]
`System.IO.Directory` lives in the `System.IO.FileSystem.dll` assembly on .NET Core. This is different from .NET Framework where it lived in `mscorlib` (and so was automatically loaded). To load the assembly:
```Python
import clr
clr.AddReference("System.IO.FileSystem")
```
Note that .NET Core provides a facade assembly for `mscorlib` so you could also add a reference to `mscorlib` (although you may end up loading many more assemblies if you do this).

See https://ironpython.net/documentation/dotnet/ for additional information on loading assemblies.

**Comment by kellyelton** [comment]
Thanks for all the details.

When I use IronPython on .net framework it loads those assemblies automatically, so I don't have to import 'mscorelib'.

The documentation says that those libraries are only loaded when using ipy.exe though.

Any of the following solutions would resolve this ticket I believe:
1) Update the documentation to explaining that no assemblies are loaded for dotnet core, but they are for .net framework.
2) Load the facade assembly mscorelib for dotnetcore
3) Stop loading mscorelib and system.dll assemblies for .netframework to match up with the documentation

**Comment by slozier** [comment]
Thanks for the suggestions:

> 1. Update the documentation to explaining that no assemblies are loaded for dotnet core, but they are for .net framework.

Updating the documentation is probably the best course of action. Note that it's not loading no assemblies, but it's loading the assemblies that contain some core types (`string` and `Debug`). In practice this means that `System.Private.CoreLib` is what gets loaded on .NET Core. Hopefully I can figure out how to make it load `System.Runtime` instead since that's the assembly that's documented on the .NET docs site.

> 2. Load the facade assembly mscorelib for dotnetcore

While this would give the "same" API surface as .NET Framework it would also load in something like an 50 extra assemblies which I think is undesirable.

> 3. Stop loading mscorelib and system.dll assemblies for .netframework to match up with the documentation

This would likely be a break everyone that uses IronPython.
