### ISSUE TITLE
how to import a generic class of C#，like "ChannelFactory<TChannel>"

### ISSUE THREAD

**Issue by starshift3** [IronLanguages/ironpython2#723]
### Prerequisites

The issue tracker is used to report bugs and request new features, NOT to ask questions.

Questions should be posted to the users mailing list which can be accessed at 
https://ironpython.groups.io/g/users. 

* [ ] Are you running the latest version? 
D:\Programs\Python\IronPython 2.7>ipy.exe -v
IronPython 2.7.10 (2.7.10.1000)
[.NETFramework,Version=v4.5 on .NET Framework 4.8.4180.0 (64-bit)]

* [ ] Are you reporting to the correct repository?
* [ ] Did you perform a cursory search?
Yes
### Description

[Description of the bug or feature]

how to import a generic class of C#，like "ChannelFactory < TChannel >"?
I want to import a generic class of C#, ChannelFactory < TChannel > from "System.ServiceModel", then create a ChannelFactory < TChannel > instance。
But, "System.ServiceModel.dll" has a interface "ChannelFactory" and a generic class "ChannelFactory < TChannel >",
I can't import the "ChannelFactory < TChannel >" correctly.
![微信截图_20200722124425](https://user-images.githubusercontent.com/44994023/88135431-9be5d180-cc19-11ea-87be-0917b53c95a9.png)
![微信截图_20200722124506](https://user-images.githubusercontent.com/44994023/88135468-b1f39200-cc19-11ea-94f8-4d0e657ec95d.png)

```Python
# coding=utf8
import clr

clr.AddReferenceToFileAndPath("C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\/v3.0\System.ServiceModel")

from System.ServiceModel import *

if __name__ == '__main__':
    endpointAddress = EndpointAddress("http://localhost")
    print endpointAddress
    channelFactory = ChannelFactory[TChannel]("MyEndpoint", endpointAddress)
    channel = channelFactory.CreateChannel()
```

```
"D:\Programs\Python\IronPython 2.7\ipy.exe" D:/Git/kuanzhai/python/test.py
http://localhost/
Traceback (most recent call last):
  File "D:/Git/kuanzhai/python/test.py", line 11, in <module>
NameError: global name 'TChannel' is not defined

进程已结束,退出代码1
```

```
# coding=utf8
import clr

clr.AddReferenceToFileAndPath("C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\/v3.0\System.ServiceModel")

from System.ServiceModel import *

if __name__ == '__main__':
    endpointAddress = EndpointAddress("http://localhost")
    print endpointAddress
    channelFactory = ChannelFactory("MyEndpoint", endpointAddress)
    channel = channelFactory.CreateChannel()
    # channelFactory.CreateChannel().ReceiveFile("")
```

```
"D:\Programs\Python\IronPython 2.7\ipy.exe" D:/Git/kuanzhai/python/test.py
http://localhost/
Traceback (most recent call last):
  File "D:/Git/kuanzhai/python/test.py", line 11, in <module>
TypeError: Cannot create instances of ChannelFactory because it is abstract

进程已结束,退出代码1
```

**Comment by slozier** [comment]
The `TChannel` generic needs to be defined. A quick search gives some examples of how to use `ChannelFactory` with IronPython:
- http://gui-at.blogspot.com/2009/11/wcf-service-in-pure-ironpython.html
- http://gui-at.blogspot.com/2009/10/wcf-service-in-ironpython.html
- https://rocky1978.wordpress.com/2011/01/30/ironpython-implement-a-wcf-client/
- https://segmentfault.com/a/1190000000623432

**Comment by starshift3** [comment]
> The `TChannel` generic needs to be defined. A quick search gives some examples of how to use `ChannelFactory` with IronPython:
> 
> * http://gui-at.blogspot.com/2009/11/wcf-service-in-pure-ironpython.html
> * http://gui-at.blogspot.com/2009/10/wcf-service-in-ironpython.html
> * https://rocky1978.wordpress.com/2011/01/30/ironpython-implement-a-wcf-client/
> * https://segmentfault.com/a/1190000000623432

Thank you.
I got it wrong before. I think the TChannel is a native class of C# in "System.ServiceModel.dll"，which I can use directly.
