### ISSUE TITLE
spacy error 'no module named spacy' / Ironpython

### ISSUE THREAD

**Issue by gazakhova** [IronLanguages/ironpython2#730]
###I am trying to run a Python script with Spacy NER model on C# using Dynamic Py.

1. I used following C# source code:
```
using System;
using IronPython.Hosting;
using System.Collections.Generic;
using System.Text;

namespace PythonTest
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Python integrieren");
            Console.ReadLine();

            var engine = Python.CreateEngine();
            try
            {
                engine.ExecuteFile(@"C:\Users\Admin\source\repos\DynamicPy\script.py");
            }
            catch (Exception ex)
            {
                Console.WriteLine("Python wurde integriert!" + ex.Message);
            }

            Console.WriteLine("Ende");
            Console.ReadLine();
        }
    }
}

```
2. Then I created a simple python code for Spacy's Named Entity Recognition:

```
import spacy
nlp = spacy.load("en_core_web_sm")
text = ("This is an example text.")

doc = nlp(text)
for entity in doc.ents:
    print(entity.label_, ": ", entity.text)
```

** I expected that Spacy's model would be read via C # and relevant entities would be recognized. 

**But I get the error ` 'no module named spacy'`

** 
I am using: 
Visual Studio 2019
Python: 3.7.5
Spacy:  v2.3.2
IronPython: 2.7

**Comment by slozier** [comment]
You need to include the path to the `spacy` module:
```C#
var paths = engine.GetSearchPaths();
paths.Add(path); // path to the module
engine.SetSearchPaths(paths);
```

**Comment by gazakhova** [comment]
> You need to include the path to the `spacy` module:
> 
> ```cs
> var paths = engine.GetSearchPaths();
> paths.Add(path); // path to the module
> engine.SetSearchPaths(paths);
> ```

It worked. Thanks! Now I get the error 'no module named __future__'. Would you have any suggestions to solve this error?

**Comment by slozier** [comment]
`__future__` is a standard library module, did you include the standard library in the search paths?

**Comment by gazakhova** [comment]
> `__future__` is a standard library module, did you include the standard library in the search paths?

Thanks for your reply!
Now I included the standard library module as well. The next issue is 'invalid syntax', if I don't import from __future__ import unicode_literals, print_function and plac 

![image](https://user-images.githubusercontent.com/56873238/91301016-8594dd80-e7a4-11ea-8a55-29060cbaac1f.png)

If I import plac I get this error 'unexpected token ',' '

![image](https://user-images.githubusercontent.com/56873238/91301170-c42a9800-e7a4-11ea-9eab-d95e3e764b1e.png)

I use anaconda. Can anaconda cause the problem?

**Comment by slozier** [comment]
Yes, using anaconda can cause the problem. IronPython 2 is Python 2 and Anaconda 3 is Python 3. Python 2 and 3 are not compatible so this will not work.
