### ISSUE TITLE
.NET 5 support

### ISSUE THREAD

**Issue by StevenGranados** [IronLanguages/ironpython2#731]
### Description

I have run into an issue where IronPython can't find the encoding 932 in > .NET 5 preview 6. The `Encoding.RegisterProvider(CodePagesEncodingProvider.Instance)` call in StringOps.cs is behind a `#if NETCOREAPP || NETSTANDARD` and therefore isn't called.
I think the issue is probably to support .NET 5 in this case.

**Comment by slozier** [comment]
The `#if NETCOREAPP` also works for .NET 5 so the issue is not with `Encoding.RegisterProvider(CodePagesEncodingProvider.Instance)` not being called. It looks like it is the call to `Encoding.WindowsCodePage` that has started failing.

**Comment by slozier** [comment]
Ah, I know what the issue is. Previously `Encoding.GetEncodings` only returned the core codecs. Now that it returns all registered encodings it's suddenly hitting an encoding (932) where the call to `WindowsCodePage` fails.
