### ISSUE TITLE
Passing by reference to COM object

### ISSUE THREAD

**Issue by timrutter** [IronLanguages/ironpython2#737]
I’m trying to access a com object written in C in python script in Dynamo which uses IronPython. I have successfully managed to load the com object and the function calls seem to work (no errors or exceptions) but when I use the functions with parameters passed by reference, I only ever get zero returned:

t = System.Type.GetTypeFromProgID("myComObject")
o = System.Activator.CreateInstance(t)

o.Open("afile") <==the com object needs to open a file to be of use
aNumber=0
o.GetAValue(0,aNumber);
The signature of the GetAValue function is defined as:

short GetAValue(short value1, short* value2)
The return value indicating success (always zero) and the second parameter being the value i’m interested in.

aNumber is always zero. The exact same script (with only changing the functions to load the com object) when ran using spyder using python 3.6 works just fine and I get a non zero value returned as expected.

I have asked the developers of the com object to confirm that the functions are being called as expected when called from IronPython. They have debugged the code and have proved that the value is being passed in and set to a non-zero value BUT when it the function returns back to the script, it is being set back to a default value. We have both independently tried passing the value by clr reference and this just throws an error.

s= clr.Reference[int]()
o.GetAValue (0,s)
ValueError: Could not convert argument 0 for call to GetAValue

Is this a bug in the way it is passing ref parameters?

**Comment by slozier** [comment]
Have you tried matching the data type?
```Python
s = clr.Reference[System.Int16]()
o.GetAValue(0,s)
```
It's entirely possible there's is a bug...

**Comment by timrutter** [comment]
that’s solved it.  Thanks a lot.
