### ISSUE TITLE
ctypes.windll.winmm.mciSendStringA behaves incorrectly

### ISSUE THREAD

**Issue by Raffro** [IronLanguages/ironpython2#748]
### Description
I have a little application, which should act as a voicerecorder. Therefore I use the library ctypes. I wrote the application and tested it with python 2.7 and it worked fine. As a result i got an wav file which was playable.

But with ironpython I always get an error when trying to open a new type waveaudio. With this little code snippet, the problem is reproduceable (and working with python 2.7)

### Steps to Reproduce
```
import ctypes

mciSendString = ctypes.windll.winmm.mciSendStringA
mciGetErrorString=ctypes.windll.winmm.mciGetErrorStringA

OpenCmd='open new type waveaudio alias 1337 wait'


buffer = ctypes.c_buffer(255)
errorcode = mciSendString(OpenCmd, buffer, 254, 0)

if errorcode:   # There was an error
    mciGetErrorString(errorcode, buffer, 254)

print(errorcode)
print(buffer.value)
```

I get the output:
292
Der Befehl erfordert einen Alias-, Datei-, Treiber- oder Gerätenamen.

With python 2.7 I get the expected output:
0
1

### Versions

IronPython 2.7.10 2.7.10.0 on .NET 4.0.30319.42000

**Comment by slozier** [comment]
With IronPython, strings are actually `unicode`. The solution to your issue is to prefix your `OpenCmd` string with `b` to ensure you have a `bytes` object:
```Python
OpenCmd = b'open new type waveaudio alias 1337 wait'
```

**Comment by Raffro** [comment]
Thank you that helped!
