### ISSUE TITLE
IronPython incompatible with .NET 5

### ISSUE THREAD

**Issue by JohnTenney** [IronLanguages/ironpython2#751]
### Prerequisites
Install .NET 5 RC 2

### Description
Simple import commands fail with .NET 5

### Steps to Reproduce
issue the command "import collections" to the interpeter

**Expected behavior:**
Should return without error

**Actual behavior:**
>>> import collections
Traceback (most recent call last):
  File "c:\xxxi\bin\Debug\net5.0-windows\win10-x64\Lib\collections.py", line 24, in <module>
SystemError: The type initializer for 'CodecsInfo' threw an exception.

### Versions

IronPython 2.7.10

**Comment by slozier** [comment]
I think this is the same as https://github.com/IronLanguages/ironpython2/issues/731? Did you try with 2.7.11-candidate1?

**Comment by JohnTenney** [comment]
Yes, this is resolved with 2.7.11. Thanks!
