### ISSUE TITLE
MSI installer of 2.7.10 fails and says a newer version of IronPython is already installed

### ISSUE THREAD

**Issue by jmartens** [IronLanguages/ironpython2#754]
### Prerequisites

The issue tracker is used to report bugs and request new features, NOT to ask questions.

Questions should be posted to the users mailing list which can be accessed at 
https://ironpython.groups.io/g/users. 

* [ ] Are you running the latest version?
* [X] Are you reporting to the correct repository?
* [X] Did you perform a cursory search?

### Description

MSI installer of 2.7.10 fails and says a newer version of IronPython is already installed, which is not the case, although other Python versions are present

![image](https://user-images.githubusercontent.com/593327/99642900-55c83f80-2a4c-11eb-8c23-ceb233cbaaba.png)

### Steps to Reproduce

1. Run installer
2. Observe error

**Expected behavior:** [What you expected to happen]
Installation of IronPython 2.7.10 finishing successfully

**Actual behavior:** [What actually happened]
See description

### Versions

You can get this information from executing `ipy -V`.
N/A

**Comment by jmartens** [comment]
Apparently 2.7.1 was installed, which should not be considered a newer release IMHO. I removed it using PowerShell as it did not appear in the application list of Windows like below.

```
PS C:\WINDOWS\system32> $MyApp = Get-WmiObject -Class Win32_Product | Where-Object{$_.Name -eq "IronPython 2.7.1"}

PS C:\WINDOWS\system32> $MyApp


IdentifyingNumber : {BD40C061-3706-4D25-A9C5-662105E1F135}
Name              : IronPython 2.7.1
Vendor            : IronPython Team
Version           : 2.7.1100
Caption           : IronPython 2.7.1




PS C:\WINDOWS\system32> $MyApp.Uninstall()


__GENUS          : 2
__CLASS          : __PARAMETERS
__SUPERCLASS     : 
__DYNASTY        : __PARAMETERS
__RELPATH        : 
__PROPERTY_COUNT : 1
__DERIVATION     : {}
__SERVER         : 
__NAMESPACE      : 
__PATH           : 
ReturnValue      : 0
PSComputerName   : 




PS C:\WINDOWS\system32> $MyApp = Get-WmiObject -Class Win32_Product | Where-Object{$_.Name -eq "IronPython 2.7.1"}

PS C:\WINDOWS\system32> echo $MyApp
```

After removal of version 2.7.1 I was able to install and run IronPython succesfully:
![image](https://user-images.githubusercontent.com/593327/99645096-118a6e80-2a4f-11eb-8401-20272409df9e.png)

**Comment by jmartens** [comment]
The 2.7.10 version gives the following output in PowerShell:

```(PowerShell)
PS C:\WINDOWS\system32> $MyApp = Get-WmiObject -Class Win32_Product | Where-Object{$_.Name -eq "IronPython 2.7.10"}

PS C:\WINDOWS\system32> echo $MyApp


IdentifyingNumber : {3BBB93E1-EA9E-48A7-8315-CAD2FE2A6608}
Name              : IronPython 2.7.10
Vendor            : IronPython Team
Version           : 2.7.10.1000
Caption           : IronPython 2.7.10
```

Look at both version numbers reported, apparently the one from 2.7.1 (`2.7.1100`) is higher than 2.7.10 (`2.7.10.1000`). Did you make a mistake with the version number of 2.7.1 perhaps?

**Comment by slozier** [comment]
Same issue as https://github.com/IronLanguages/ironpython2/issues/427. The versioning scheme was changed with 2.7.7 due to technical reasons (the version number would have become 2.7.71000 which is invalid since each part must be <= 65535).
