### ISSUE TITLE
Huge memory usage (leak) after switching to .NET5

### ISSUE THREAD

**Issue by Dunge** [IronLanguages/ironpython2#757]
### Description

I ported an application from .Net Framework 4.7.2 to .NET5, and the IronPython nuget from 2.7.10 to 2.7.11. No other changes has been done in the project except of course updating all dependencies to be compatible with .NET5.

The application is creating a `ScriptEngine` once, and compiling a bunch of python scripts (`CompiledCode`) at boot.

Then it periodically create a `ScriptScope`, call `SetVariable` on it and then call `Execute()` on the `CompiledCode` passing the `ScriptScope` as argument.

Previously, the application working set would hover at around 200MB usage, and would stay stable indefinitely (weeks, months). Now, the application working set memory increase constantly as if the garbage collector is missing something. After 48h, the application reach over 1.1GB and it won't stop growing until restarted. This is on a development server, so production would probably crash the machine in no time.

![image](https://user-images.githubusercontent.com/6548184/100794997-55d12380-33ec-11eb-9a47-07c0e530249e.png)

I used Visual Studio Diagnostic Tools to take memory snapshots and compare them. The objects that seems to have the biggest memory differences are `Microsoft.Scripting.ScopeVariableIgnoreCase` and `Microsoft.Scripting.ScopeVariable` who seems to be kept active via `Microsoft.Scripting.ScopeStorage`. But to be honest, I'm no expert at memory diagnostics so I'm not too sure what I'm looking at.

The `ScriptScope` doesn't implement IDisposable so I would expect the garbage collector to free the memory after the script execution and the method scope to end.

**Expected behavior:** Memory usage stay constant

**Actual behavior:** Memory usage is in constant rise

### Versions

IronPython 2.7.11

**Comment by slozier** [comment]
I tried a simple program following the description and did not observe any memory increase, is there any additional information you could provide that would help replicate the issue? Here is my simple program:
```C#
var code = engine.CreateScriptSourceFromString("y = pow(x, 2)");
while (true)
{
    var scope = engine.CreateScope();
    scope.SetVariable("x", 2);
    code.Execute(scope);
    int y = scope.GetVariable("y");
    Debug.Assert(y == 4);
}
```

**Comment by Dunge** [comment]
Thanks for the extremely quick reply. To be honest, I'm still trying to wrap my head around the circumstances that cause the problem shows itself. I might have created this issue a bit too fast and the problem might not come from IronPython directly, but only as a result of it's scope unable to be garbage collected because of something else.

The variable I'm injecting in the scope is a class with dependencies that are instanced by the dependency injection container, and I believe it might be the culprit (even though it is a singleton and nothing should prevent deleting it). I'll keep digging around and see what I can find.

**Comment by Dunge** [comment]
Outside circumstances, sorry for wasting your time.

**Comment by slozier** [comment]
No worries, glad you resolved it.
