### ISSUE TITLE
TargetFrameworks net5.0-windows missing

### ISSUE THREAD

**Issue by nesaboz** [IronLanguages/ironpython2#767]
### Prerequisites

* [x ] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?

### Description

master branch to include net5.0-windows as a TargetFramework

### Steps to Reproduce

**Expected behavior:** cloned repo, built, and expected to see `net5.0-windows` folder created

**Actual behavior:** latest is netcoreapp3.1

### Versions

2.7.11

**Comment by slozier** [comment]
Can I ask why you need a `net5.0-windows` target? The `netcoreapp3.1` assemblies should work fine with `net5.0`.
