### ISSUE TITLE
Error importing pytesseract in Python script 

### ISSUE THREAD

**Issue by teckdj** [IronLanguages/ironpython2#775]
### Prerequisites
pytesseract needs to installed
IronPython nuget Packages needs to be installed
tesseract should be installed
Platform is windows 10.
   
### Description
unable to execute the python script, if I am importing 'pytesseract' module,  it give an exception - invalid syntax 
while running this is dotnet

[Description of the bug or feature]

### Steps to Reproduce

1. python script

    import pytesseract as tc
    from PIL import Image
    
    def Simple():
      print ('Hello from Python')
      tc.pytesseract.tesseract_cmd = 'C:\\Program Files\\Tesseract-OCR\\tesseract.exe'
      tcvn = tc.get_tesseract_version()
      print('Tesseract Version  is : ' + str(tcvn))

      Simple()

2. C# code

             var engine = Python.CreateEngine();
              var mainfile = @"C:\Code\tesserPtoD.py";

            var searchPaths = engine.GetSearchPaths();
            searchPaths.Add(@"C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\Lib\site-packages");
            engine.SetSearchPaths(searchPaths);
            var scope = engine.CreateScope();
            ScriptSource source = engine.CreateScriptSourceFromFile(mainfile);
            source.Execute(scope);

3.  Error is raised when executing -  source.Execute(scope);
Error details -
Microsoft.Scripting.SyntaxErrorException
  HResult=0x80131500
  Message=invalid syntax
  Source=IronPython

It looks like its raising error in pytesseract.py file at tab no. 89.
. 
**Expected behavior:** 
The Program should have executed successfully and Tesseract Version should been listed.

**Actual behavior:** 
Runtime - Error is raised 

### Versions
Python version 3.6.6
IronPython version 2.7.11

**Comment by slozier** [comment]
You can't reference Python 3 modules from IronPython 2, the two languages are incompatible. You're going to need a Python 2.7 version of it (and even then I'm not sure if it will work, I believe Pillow has some CPython dependencies).

**Comment by teckdj** [comment]
Thanks for your response Slozier. 
Will this issue be addressed in IronPython 3?

**Comment by slozier** [comment]
The syntax error (string interpolation) would be fixed by IronPython 3.6, however the current target for IronPython 3 is 3.4 so it may be some time before we get there.

If you want to use IronPython 2, you could try installing the Python 2.7 version of pytesseract which would solve the syntax issue (although I have no idea if it will work).

**Comment by teckdj** [comment]
Hello Slozier,

As explained by you I tried running script against python 2.7 of pytesseract. The py script runs successfully on the python 2.7 shell command. however it's fails running under Iron Python.
Now I am getting error - IronPython.Runtime.Exceptions.ImportException: 'No module named Image' 
Source is - Microsoft.Dynamic 
  at Microsoft.Scripting.Runtime.LightExceptions.ThrowException(LightException lightEx) ....

I did add the modules path for 'Image' in the scope still getting the same error.

Any help is much appreciated.

**Comment by slozier** [comment]
It looks like pytesseract requires the `PIL.Image` module which is largely implemented as a CPython extension. Unfortunately this will now work with IronPython.

**Comment by teckdj** [comment]
Thanks for checking.  Do you have any plan on adding the enhancement in IronPython to load library having cpython extension?

**Comment by slozier** [comment]
While I'd love to revive [Ironclad](https://github.com/IronLanguages/ironclad) (which is a project that does just that) I unfortunately don't have any time to work on it personally.
