### ISSUE TITLE
What is the best version of Python to  use for IronPython 2.7.11

### ISSUE THREAD

**Issue by gpadvorac** [IronLanguages/ironpython2#781]
I don't see any documentation of the best dependency versions to install with a specific version of IronPython. It would be helpful to put this upfront somewhere.  

For example, for IronPython 2.7.11 should I install Python 2.7?  I currently have 3.8.8 installed and I dont know if thats why I get the errors:

IronPython.Runtime.Exceptions.ImportException - No module named requests
or
IronPython.Runtime.Exceptions.ImportException - No module named urllib.error

Thank  you.

**Comment by slozier** [comment]
I'm not sure what you mean. IronPython is an alternate implementation of Python so it does not have a dependency on a Python installation...

**Comment by gpadvorac** [comment]
I may have framed the question wrong, but it seems that different versions of IronPython support different versions of Python.  For example, if I have IronPython 2.7.11 will there be any issues with calling a scripts from Python 3.8.8 and the modules that may be imported for that script?

**Comment by pankon** [comment]
If you're using a large product with tons of memory, I would stick to 2.6
