### ISSUE TITLE
IronPhyton wpf removed from Visual Studio 16.9.4

### ISSUE THREAD

**Issue by JetteChristensen** [IronLanguages/ironpython2#782]
In the latest Visual Studio 2019 v. 16.9.4 it is no longer possible to select IronPhyton wpf application project, when you create a new project.

* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
* [X] Did you perform a cursory search?

1. Open Visual Studio 2019
2. Select create a new project
3. Verify that IronPhyton WPF Application is missing.

**Expected behavior:**  Expected that IronPhyton wpf application is there to select.

**Actual behavior:** IronPhyton wpf application is missing

### Versions

You can get this information from executing `ipy -V`.
Visual Studio 2019 v, 16.9.4
Phyton 3 64 bit 3.7.8
IronPhyton 2.7
IronPhyton 3,4,0

**Comment by slozier** [comment]
We have no control over what Visual Studio does, maybe you could try asking on the PTVS repo https://github.com/microsoft/PTVS
