### ISSUE TITLE
Has 2.7.11 been validated against .NET 6?

### ISSUE THREAD

**Issue by JohnTenney** [IronLanguages/ironpython2#802]
I have an application running IronPython 2.7.11 with .NET 5 without problems. But it isn't running successfully in .NET 6. I don't have a small test program to demo the issue--I was just wondering if 2.7.11 has been validated to work with .NET 6 yet?

**Comment by uffebjorklund** [comment]
@JohnTenney I have a .NET application that runs `<PackageReference Include="IronPython.StdLib" Version="3.4.0-alpha1" />` 
Not really what you asked about, but at least  that version works with .NET6.

**Comment by slozier** [comment]
I am aware of some small incompatibilities with .NET 6 but (hopefully) none that should prevent an app from working. If you have more info it would be useful as I'm slowly preparing the next release...

**Comment by JohnTenney** [comment]
Looks like the problem was that ctypes.windll.user32.GetSystemMetrics now returns null.

**Comment by slozier** [comment]
I think this is caused by one of the incompatibilities I mentioned. I should have a fix which I can port over from the ipy3 repo.
