### ISSUE TITLE
IronPython.StdLib 2.7.12 is missing on nuget.org

### ISSUE THREAD

**Issue by cwensley** [IronLanguages/ironpython2#806]
### Description

IronPython 2.7.12 is published on nuget.org, but IronPython.StdLib 2.7.12 is not yet there.  

Perhaps this was an oversight?

**Comment by slozier** [comment]
I hadn't published it because it's identical to 2.7.11, however someone suggested I publish it anyway to avoid confusion. I guess I should have listened. On NuGet now! :smile:
