### ISSUE TITLE
What is the funciton of Mono.Unix in version 2.7.12

### ISSUE THREAD

**Issue by bnuzhouwei** [IronLanguages/ironpython2#824]
I find use Mono.Unix in version 2.7.12. What is function of Mono.Unix.

The IronPython could start and run with out libMono.Unix.so.

Where is the scene require the libMono.Unix.so?

Why add such a big dependence?

**Comment by slozier** [comment]
I believe it's only required on .NET (Core). Mostly used in the posix module.
